# Assignment 1

![](https://media.giphy.com/media/xT9C25UNTwfZuk85WP/giphy-downsized-large.gif)

Remember the rules of ~Fight~ Code Club:
1. ALWAYS DOCUMENT
2. Cite resources that you use (paste links)
3. Include the names people who you worked with
4. Be neat and organized

## Scrape and Clean data

Based on you proposal, scrape or collect your data:

1. One variable must be either: (40 pts)
    1. scraped from the web OR;
    2. collected from an API AND you must create one new variable that is "new" to the best of your knowledge (combination of other variables representing something new).

2. You must have at least 3 variables, but you may include as many as you want into you final dataset. Likely, you will want to include more to make graphs and regressions. (30pts)

3. You must *be able* to run a regression that makes some sense with this data (the regression doesn't have to be a complete model). Briefly describe one regression you would run with your variables. (**DO NOT** run a regression, yet). (15pts)

4. You must have one combined and cleaned dataset (15 pts)

You must submit one python notebook on how you scraped/gathered data from an api, and how you combined and cleaned you data. I should be able to run your code and reproduce your final data set.  

The other variables that you choose to include do not have to be collected by API or webscraped, but you do have to combine the files and clean the dataset with python.

Thus, you must submit:
- Your finalized data set (only one) (note: you may add more variables in the future).
- Your documented python notebook
- Any associated data files needed to produce the final dataset.

You will be evaluated on:
- Completeness of the data
- Quality of the code 
- The creativity of the new variable/webscraped data you gather

Be sure to upload ALL associated files for your code to run. I will run your code from beginning to end - make it easy for me to replicate your code.

# API Project - Bus Bunching
### Multi-agency Comparsion (WMATA, MBTA, MTA)
Question: What route and temporal factors are associated with bus bunching on high-frequency corridors, and do these relationships vary across different transit agencies (NYC, Boston, and DC)?

In [45]:
import pandas as pd
import numpy as np
import requests
import ratelim
import tenacity

### 1) WMATA API
#### Bus Routes: D40, D60, D80, C53, C61, D20

In [46]:
WMATA_KEY = "5ec08fcd21744590b1a0f655710c4c91"

In [47]:
wmata_url = "https://api.wmata.com/Bus.svc/json/jBusPositions"
wmata_params = {"RouteID": "D40"}  
wmata_headers = {"api_key": WMATA_KEY}

requests.get(wmata_url, params=wmata_params, headers=wmata_headers)

In [48]:
wmata_response = requests.get(wmata_url, params=wmata_params, headers=wmata_headers)
wmata_response.json()

{'BusPositions': [{'VehicleID': '5536',
   'Lat': 38.89257049560547,
   'Lon': -77.02388763427734,
   'Deviation': 8.0,
   'DateTime': '2026-03-31T20:48:08',
   'TripID': '28868020',
   'RouteID': 'D40',
   'DirectionNum': 1,
   'DirectionText': 'SOUTH',
   'TripHeadsign': 'ARCHIVES',
   'TripStartTime': '2026-03-31T19:48:00',
   'TripEndTime': '2026-03-31T20:37:00',
   'BlockNumber': 'M615'},
  {'VehicleID': '5517',
   'Lat': 38.90422075445002,
   'Lon': -77.02191162109375,
   'Deviation': 7.0,
   'DateTime': '2026-03-31T20:48:09',
   'TripID': '32430020',
   'RouteID': 'D40',
   'DirectionNum': 1,
   'DirectionText': 'SOUTH',
   'TripHeadsign': 'ARCHIVES',
   'TripStartTime': '2026-03-31T20:00:00',
   'TripEndTime': '2026-03-31T20:49:00',
   'BlockNumber': 'M619'},
  {'VehicleID': '5513',
   'Lat': 38.96554347446987,
   'Lon': -77.02764769962856,
   'Deviation': 11.0,
   'DateTime': '2026-03-31T20:47:57',
   'TripID': '163020',
   'RouteID': 'D40',
   'DirectionNum': 0,
   'DirectionText': 'NORTH',
   'TripHeadsign': 'SILVER SPRING',
   'TripStartTime': '2026-03-31T20:00:00',
   'TripEndTime': '2026-03-31T20:51:00',
   'BlockNumber': 'M624'},
  {'VehicleID': '7258',
   'Lat': 38.91591741524491,
   'Lon': -77.02191925048828,
   'Deviation': 1.0,
   'DateTime': '2026-03-31T20:47:53',
   'TripID': '608020',
   'RouteID': 'D40',
   'DirectionNum': 1,
   'DirectionText': 'SOUTH',
   'TripHeadsign': 'ARCHIVES',
   'TripStartTime': '2026-03-31T20:12:00',
   'TripEndTime': '2026-03-31T21:01:00',
   'BlockNumber': 'M169'},
  {'VehicleID': '5521',
   'Lat': 38.96691557940315,
   'Lon': -77.02753912233838,
   'Deviation': -2.0,
   'DateTime': '2026-03-31T20:48:15',
   'TripID': '5155020',
   'RouteID': 'D40',
   'DirectionNum': 0,
   'DirectionText': 'NORTH',
   'TripHeadsign': 'SILVER SPRING',
   'TripStartTime': '2026-03-31T20:12:00',
   'TripEndTime': '2026-03-31T21:03:00',
   'BlockNumber': 'M625'},
  {'VehicleID': '5509',
   'Lat': 38.92843784430088,
   'Lon': -77.02314562675281,
   'Deviation': 2.0,
   'DateTime': '2026-03-31T20:47:48',
   'TripID': '20886020',
   'RouteID': 'D40',
   'DirectionNum': 0,
   'DirectionText': 'NORTH',
   'TripHeadsign': 'SILVER SPRING',
   'TripStartTime': '2026-03-31T20:24:00',
   'TripEndTime': '2026-03-31T21:15:00',
   'BlockNumber': 'M604'},
  {'VehicleID': '5520',
   'Lat': 38.98187128702799,
   'Lon': -77.02654266357422,
   'Deviation': 3.0,
   'DateTime': '2026-03-31T20:48:15',
   'TripID': '7858020',
   'RouteID': 'D40',
   'DirectionNum': 1,
   'DirectionText': 'SOUTH',
   'TripHeadsign': 'ARCHIVES',
   'TripStartTime': '2026-03-31T20:36:00',
   'TripEndTime': '2026-03-31T21:25:00',
   'BlockNumber': 'M608'},
  {'VehicleID': '5512',
   'Lat': 38.893245,
   'Lon': -77.023895,
   'Deviation': 24.0,
   'DateTime': '2026-03-31T20:48:14',
   'TripID': '34445020',
   'RouteID': 'D40',
   'DirectionNum': 0,
   'DirectionText': 'NORTH',
   'TripHeadsign': 'SILVER SPRING',
   'TripStartTime': '2026-03-31T20:36:00',
   'TripEndTime': '2026-03-31T21:27:00',
   'BlockNumber': 'M614'},
  {'VehicleID': '5533',
   'Lat': 38.99361801147461,
   'Lon': -77.0296401977539,
   'Deviation': 0.0,
   'DateTime': '2026-03-31T20:48:00',
   'TripID': '13320020',
   'RouteID': 'D40',
   'DirectionNum': 1,
   'DirectionText': 'SOUTH',
   'TripHeadsign': 'ARCHIVES',
   'TripStartTime': '2026-03-31T20:48:00',
   'TripEndTime': '2026-03-31T21:37:00',
   'BlockNumber': 'M622'}]}

#### Vars Used: 
- `Deviation` — the primary outcome, minutes late/early so no GTFS needed
- `DateTime` — timestamp will be used for peak hour flag
- `RouteID`, `DirectionNum`, `VehicleID`, `TripID` — route/trip identifiers (`DirectionNum`, 0=North 1=South)
- `TripStartTime` — scheduled headway, will be used to calc the gap between consecutive trips
- `Lat`, `Lon` — Vehicle position

In [49]:
wmata_fields = {
    'VehicleID': 'vehicle_id',
    'Lat': 'lat',
    'Lon': 'lon',
    'Deviation': 'deviation',
    'DateTime': 'timestamp',
    'TripID': 'trip_id',
    'RouteID': 'route_id',
    'DirectionNum': 'direction',
    'TripStartTime': 'trip_start_time'
}

wmata_positions = wmata_response.json()['BusPositions']

df = pd.DataFrame(wmata_positions)[list(wmata_fields.keys())].rename(columns=wmata_fields)
df['agency'] = 'WMATA'

print(df)
print(df.dtypes) #Checks for var types (timestamp and trip_start_time)

  vehicle_id        lat        lon  deviation            timestamp   trip_id  \
0       5536  38.892570 -77.023888        8.0  2026-03-31T20:48:08  28868020
1       5517  38.904221 -77.021912        7.0  2026-03-31T20:48:09  32430020
2       5513  38.965543 -77.027648       11.0  2026-03-31T20:47:57    163020
3       7258  38.915917 -77.021919        1.0  2026-03-31T20:47:53    608020
4       5521  38.966916 -77.027539       -2.0  2026-03-31T20:48:15   5155020
5       5509  38.928438 -77.023146        2.0  2026-03-31T20:47:48  20886020
6       5520  38.981871 -77.026543        3.0  2026-03-31T20:48:15   7858020
7       5512  38.893245 -77.023895       24.0  2026-03-31T20:48:14  34445020
8       5533  38.993618 -77.029640        0.0  2026-03-31T20:48:00  13320020

  route_id  direction      trip_start_time agency
0      D40          1  2026-03-31T19:48:00  WMATA
1      D40          1  2026-03-31T20:00:00  WMATA
2      D40          0  2026-03-31T20:00:00  WMATA
3      D40          1  2026-03-31T20:12:00  WMATA
4      D40          0  2026-03-31T20:12:00  WMATA
5      D40          0  2026-03-31T20:24:00  WMATA
6      D40          1  2026-03-31T20:36:00  WMATA
7      D40          0  2026-03-31T20:36:00  WMATA
8      D40          1  2026-03-31T20:48:00  WMATA
vehicle_id          object
lat                float64
lon                float64
deviation          float64
timestamp           object
trip_id             object
route_id            object
direction            int64
trip_start_time     object
agency              object
dtype: object

In [50]:
df['timestamp'] = pd.to_datetime(df['timestamp'])
df['trip_start_time'] = pd.to_datetime(df['trip_start_time'])
print(df.dtypes)

vehicle_id                 object
lat                       float64
lon                       float64
deviation                 float64
timestamp          datetime64[ns]
trip_id                    object
route_id                   object
direction                   int64
trip_start_time    datetime64[ns]
agency                     object
dtype: object

In [51]:
routes = ['D40', 'D60', 'D80', 'C53', 'C61', 'D20']
dfs = []

for route in routes:
    wmata_response = requests.get(wmata_url, params={"RouteID": route}, headers=wmata_headers)
    wmata_positions = wmata_response.json()['BusPositions']
    df = pd.DataFrame(wmata_positions)[list(wmata_fields.keys())].rename(columns=wmata_fields)
    df['agency'] = 'WMATA'
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df['trip_start_time'] = pd.to_datetime(df['trip_start_time'])
    dfs.append(df)

wmata_df = pd.concat(dfs, ignore_index=True)

In [52]:
wmata_df

,vehicle_id,lat,lon,deviation,timestamp,trip_id,route_id,direction,trip_start_time,agency
0,5536,38.892570,-77.023888,8.0,2026-03-31 20:48:08,28868020,D40,1,2026-03-31 19:48:00,WMATA
1,5517,38.904221,-77.021912,7.0,2026-03-31 20:48:09,32430020,D40,1,2026-03-31 20:00:00,WMATA
2,5513,38.965543,-77.027648,11.0,2026-03-31 20:47:57,163020,D40,0,2026-03-31 20:00:00,WMATA
3,7258,38.915917,-77.021919,1.0,2026-03-31 20:47:53,608020,D40,1,2026-03-31 20:12:00,WMATA
4,5521,38.966916,-77.027539,-2.0,2026-03-31 20:48:15,5155020,D40,0,2026-03-31 20:12:00,WMATA
5,5509,38.928438,-77.023146,2.0,2026-03-31 20:47:48,20886020,D40,0,2026-03-31 20:24:00,WMATA
6,5520,38.981871,-77.026543,3.0,2026-03-31 20:48:15,7858020,D40,1,2026-03-31 20:36:00,WMATA
7,5512,38.893245,-77.023895,24.0,2026-03-31 20:48:14,34445020,D40,0,2026-03-31 20:36:00,WMATA
8,5533,38.993618,-77.029640,0.0,2026-03-31 20:48:00,13320020,D40,1,2026-03-31 20:48:00,WMATA
9,5515,38.902475,-77.030637,-5.0,2026-03-31 20:47:19,15851020,D60,1,2026-03-31 20:00:00,WMATA
10,5535,38.916790,-77.036507,48.0,2026-03-31 20:48:06,5460020,D60,0,2026-03-31 20:00:00,WMATA
11,5503,38.920342,-77.036499,3.0,2026-03-31 20:48:00,903020,D60,1,2026-03-31 20:15:00,WMATA
12,5524,38.973034,-77.036308,2.0,2026-03-31 20:47:50,22623020,D60,0,2026-03-31 20:15:00,WMATA
13,5532,38.952884,-77.036461,1.0,2026-03-31 20:47:48,24564020,D60,1,2026-03-31 20:30:00,WMATA
14,5534,38.928346,-77.036484,0.0,2026-03-31 20:48:08,27318020,D60,0,2026-03-31 20:30:00,WMATA
15,5505,38.903000,-77.036583,-1.0,2026-03-31 20:48:07,4652020,D60,0,2026-03-31 20:45:00,WMATA
16,5514,38.994144,-77.030891,2.0,2026-03-31 20:47:55,12041020,D60,1,2026-03-31 20:45:00,WMATA
17,7121,38.943975,-77.077453,9.0,2026-03-31 20:48:02,5323020,D80,0,2026-03-31 19:50:00,WMATA
18,4600,38.896719,-77.009064,5.0,2026-03-31 20:48:07,22144020,D80,1,2026-03-31 19:50:00,WMATA
19,4603,38.904796,-77.056602,9.0,2026-03-31 20:48:00,27483020,D80,0,2026-03-31 20:10:00,WMATA
20,4590,38.901995,-77.048744,5.0,2026-03-31 20:48:08,28579020,D80,1,2026-03-31 20:12:00,WMATA
21,4592,38.902145,-77.048780,3.0,2026-03-31 20:48:05,4608020,D80,0,2026-03-31 20:20:00,WMATA
22,4577,38.920051,-77.071354,7.0,2026-03-31 20:48:09,28666020,D80,1,2026-03-31 20:24:00,WMATA
23,4574,38.901340,-77.041019,-4.0,2026-03-31 20:47:57,28614020,D80,0,2026-03-31 20:30:00,WMATA
24,7105,38.946510,-77.078899,5.0,2026-03-31 20:47:51,7012020,D80,1,2026-03-31 20:36:00,WMATA
25,4572,38.900795,-77.017968,1.0,2026-03-31 20:47:50,27202020,D80,0,2026-03-31 20:40:00,WMATA
26,4609,38.896423,-77.008034,0.0,2026-03-31 20:48:02,30430020,D80,0,2026-03-31 20:50:00,WMATA
27,5475,38.845771,-76.987587,-2.0,2026-03-31 20:47:26,8877020,C53,1,2026-03-31 19:25:00,WMATA
28,5476,38.915939,-77.021104,21.0,2026-03-31 20:48:13,18961020,C53,0,2026-03-31 19:36:00,WMATA
29,5474,38.916161,-77.021622,11.0,2026-03-31 20:48:08,2586020,C53,0,2026-03-31 19:48:00,WMATA
30,5467,38.873827,-76.991494,9.0,2026-03-31 20:48:15,17448020,C53,1,2026-03-31 19:54:00,WMATA
31,5470,38.876438,-76.993048,1.0,2026-03-31 20:47:52,32214020,C53,1,2026-03-31 20:03:00,WMATA
32,5480,38.899961,-76.994976,6.0,2026-03-31 20:48:01,12230020,C53,0,2026-03-31 20:12:00,WMATA
33,5541,38.899224,-76.994957,7.0,2026-03-31 20:48:06,25409020,C53,1,2026-03-31 20:12:00,WMATA
34,5461,38.867005,-76.986393,10.0,2026-03-31 20:48:09,33633020,C53,0,2026-03-31 20:24:00,WMATA
35,2886,38.933572,-76.994142,6.0,2026-03-31 20:48:04,19183020,C61,0,2026-03-31 20:01:00,WMATA
36,4632,38.933722,-76.994156,-2.0,2026-03-31 20:47:58,4291020,C61,0,2026-03-31 20:13:00,WMATA
37,2860,38.927647,-77.029747,11.0,2026-03-31 20:48:13,15066020,C61,1,2026-03-31 20:24:00,WMATA
38,7308,38.928695,-77.036657,6.0,2026-03-31 20:48:01,7099020,C61,0,2026-03-31 20:25:00,WMATA
39,3336,38.930547,-77.016467,4.0,2026-03-31 20:47:48,17656020,C61,1,2026-03-31 20:36:00,WMATA
40,2909,38.936871,-77.060097,3.0,2026-03-31 20:47:59,14615020,C61,0,2026-03-31 20:37:00,WMATA
41,7034,38.949692,-77.080200,-2.0,2026-03-31 20:47:54,12443020,C61,0,2026-03-31 20:49:00,WMATA
42,7181,38.898385,-76.946871,3.0,2026-03-31 20:48:04,33751020,D20,0,2026-03-31 20:00:00,WMATA
43,4716,38.900325,-77.005381,12.0,2026-03-31 20:47:52,23617020,D20,1,2026-03-31 20:18:00,WMATA
44,5482,38.899980,-76.982987,2.0,2026-03-31 20:48:03,35692020,D20,0,2026-03-31 20:20:00,WMATA
45,7190,38.899433,-76.979881,-6.0,2026-03-31 20:48:14,14243020,D20,0,2026-03-31 20:30:00,WMATA
46,7193,38.899755,-76.980751,1.0,2026-03-31 20:48:08,27986020,D20,1,2026-03-31 20:38:00,WMATA
47,7314,38.899390,-76.945858,0.0,2026-03-31 20:48:08,14830020,D20,1,2026-03-31 20:48:00,WMATA
48,7182,38.901612,-77.038542,0.0,2026-03-31 20:48:07,30307020,D20,0,2026-03-31 20:50:00,WMATA

In [53]:
print(wmata_df['route_id'].unique()) #Checking that all the routes i need are in the df

['D40' 'D60' 'D80' 'C53' 'C61' 'D20']

### 2) MBTA API
#### Bus Routes: Route 1, 23, 28, 39, 57, 66

In [54]:
MBTA_KEY = '4aa18b9edd1341e383dc8fe55a788cca'

In [55]:
#Test
mbta_url = "https://api-v3.mbta.com/vehicles"
mbta_params = {"filter[route]": "1"}
mbta_headers = {"x-api-key": MBTA_KEY}

requests.get(mbta_url, params=mbta_params, headers=mbta_headers)

In [56]:
mbta_response = requests.get(mbta_url, params=mbta_params, headers=mbta_headers)
mbta_response.json()

{'data': [{'attributes': {'bearing': 90,
    'carriages': [],
    'current_status': 'STOPPED_AT',
    'current_stop_sequence': 1,
    'direction_id': 0,
    'label': '1922',
    'latitude': 42.32983,
    'longitude': -71.08371,
    'occupancy_status': 'MANY_SEATS_AVAILABLE',
    'revenue': 'REVENUE',
    'speed': None,
    'updated_at': '2026-03-31T20:48:04-04:00'},
   'id': 'y1922',
   'links': {'self': '/vehicles/y1922'},
   'relationships': {'route': {'data': {'id': '1', 'type': 'route'}},
    'stop': {'data': {'id': '64', 'type': 'stop'}},
    'trip': {'data': {'id': '73601905', 'type': 'trip'}}},
   'type': 'vehicle'},
  {'attributes': {'bearing': 332,
    'carriages': [],
    'current_status': 'IN_TRANSIT_TO',
    'current_stop_sequence': 8,
    'direction_id': 0,
    'label': '1875',
    'latitude': 42.336768,
    'longitude': -71.077224,
    'occupancy_status': 'MANY_SEATS_AVAILABLE',
    'revenue': 'REVENUE',
    'speed': None,
    'updated_at': '2026-03-31T20:48:23-04:00'},
   'id': 'y1875',
   'links': {'self': '/vehicles/y1875'},
   'relationships': {'route': {'data': {'id': '1', 'type': 'route'}},
    'stop': {'data': {'id': '10590', 'type': 'stop'}},
    'trip': {'data': {'id': '73601895', 'type': 'trip'}}},
   'type': 'vehicle'},
  {'attributes': {'bearing': None,
    'carriages': [],
    'current_status': 'IN_TRANSIT_TO',
    'current_stop_sequence': 11,
    'direction_id': 1,
    'label': '1864',
    'latitude': 42.357648,
    'longitude': -71.092876,
    'occupancy_status': 'MANY_SEATS_AVAILABLE',
    'revenue': 'REVENUE',
    'speed': None,
    'updated_at': '2026-03-31T20:48:20-04:00'},
   'id': 'y1864',
   'links': {'self': '/vehicles/y1864'},
   'relationships': {'route': {'data': {'id': '1', 'type': 'route'}},
    'stop': {'data': {'id': '77', 'type': 'stop'}},
    'trip': {'data': {'id': '73602195', 'type': 'trip'}}},
   'type': 'vehicle'},
  {'attributes': {'bearing': 143,
    'carriages': [],
    'current_status': 'IN_TRANSIT_TO',
    'current_stop_sequence': 16,
    'direction_id': 1,
    'label': '1849',
    'latitude': 42.340768,
    'longitude': -71.081972,
    'occupancy_status': 'FEW_SEATS_AVAILABLE',
    'revenue': 'REVENUE',
    'speed': None,
    'updated_at': '2026-03-31T20:48:16-04:00'},
   'id': 'y1849',
   'links': {'self': '/vehicles/y1849'},
   'relationships': {'route': {'data': {'id': '1', 'type': 'route'}},
    'stop': {'data': {'id': '84', 'type': 'stop'}},
    'trip': {'data': {'id': '73602191', 'type': 'trip'}}},
   'type': 'vehicle'},
  {'attributes': {'bearing': None,
    'carriages': [],
    'current_status': 'STOPPED_AT',
    'current_stop_sequence': 17,
    'direction_id': 0,
    'label': '1846',
    'latitude': 42.362598,
    'longitude': -71.099434,
    'occupancy_status': 'FEW_SEATS_AVAILABLE',
    'revenue': 'REVENUE',
    'speed': None,
    'updated_at': '2026-03-31T20:48:24-04:00'},
   'id': 'y1846',
   'links': {'self': '/vehicles/y1846'},
   'relationships': {'route': {'data': {'id': '1', 'type': 'route'}},
    'stop': {'data': {'id': '101', 'type': 'stop'}},
    'trip': {'data': {'id': '73601894', 'type': 'trip'}}},
   'type': 'vehicle'},
  {'attributes': {'bearing': 341,
    'carriages': [],
    'current_status': 'STOPPED_AT',
    'current_stop_sequence': 1,
    'direction_id': 1,
    'label': '1729',
    'latitude': 42.373356,
    'longitude': -71.117745,
    'occupancy_status': 'MANY_SEATS_AVAILABLE',
    'revenue': 'REVENUE',
    'speed': None,
    'updated_at': '2026-03-31T20:48:18-04:00'},
   'id': 'y1729',
   'links': {'self': '/vehicles/y1729'},
   'relationships': {'route': {'data': {'id': '1', 'type': 'route'}},
    'stop': {'data': {'id': '110', 'type': 'stop'}},
    'trip': {'data': {'id': '73602194', 'type': 'trip'}}},
   'type': 'vehicle'}],
 'jsonapi': {'version': '1.0'}}

#### Vars Used
- `id` — vehicle_id
- `attributes.latitude`, `attributes.longitude` — lat, lon
- `attributes.direction_id` — direction (already 0/1, but doesn't tell me which direction that is)
- `attributes.updated_at` — timestamp
- `attributes.current_stop_sequence` — stop_sequence (not available in WMATA)
- `relationships.trip.data.id` — trip_id
- `relationships.route.data.id` — route_id

#### Notes
- No deviation field — must be computed from GTFS static feed in R
- I'll also need GTFS static for the direction north or south bound
- This nested unlike WMATA which was more straight forward

In [57]:
mbta_positions = mbta_response.json()['data']
mbta_positions

mbta_fields = []
for vehicle in mbta_positions:
    row = {
        'vehicle_id': vehicle['id'],
        'lat': vehicle['attributes']['latitude'],
        'lon': vehicle['attributes']['longitude'],
        'direction': vehicle['attributes']['direction_id'],
        'timestamp': vehicle['attributes']['updated_at'],
        'stop_sequence': vehicle['attributes']['current_stop_sequence'],
        'trip_id': vehicle['relationships']['trip']['data']['id'],
        'route_id': vehicle['relationships']['route']['data']['id']
    }
    mbta_fields.append(row)

mbta_df = pd.DataFrame(mbta_fields)
mbta_df['agency'] = 'MBTA'
mbta_df['timestamp'] = pd.to_datetime(mbta_df['timestamp'])

mbta_df

,vehicle_id,lat,lon,direction,timestamp,stop_sequence,trip_id,route_id,agency
0,y1922,42.329830,-71.083710,0,2026-03-31 20:48:04-04:00,1,73601905,1,MBTA
1,y1875,42.336768,-71.077224,0,2026-03-31 20:48:23-04:00,8,73601895,1,MBTA
2,y1864,42.357648,-71.092876,1,2026-03-31 20:48:20-04:00,11,73602195,1,MBTA
3,y1849,42.340768,-71.081972,1,2026-03-31 20:48:16-04:00,16,73602191,1,MBTA
4,y1846,42.362598,-71.099434,0,2026-03-31 20:48:24-04:00,17,73601894,1,MBTA
5,y1729,42.373356,-71.117745,1,2026-03-31 20:48:18-04:00,1,73602194,1,MBTA

In [58]:
mbta_df.dtypes
mbta_df['timestamp'] = mbta_df['timestamp'].dt.tz_localize(None) # Making time zone consistent
mbta_df.dtypes

vehicle_id               object
lat                     float64
lon                     float64
direction                 int64
timestamp        datetime64[ns]
stop_sequence             int64
trip_id                  object
route_id                 object
agency                   object
dtype: object

In [59]:
mbta_routes = ['1', '23', '28', '39', '57', '66']
mbta_dfs = []

for route in mbta_routes:
    mbta_response = requests.get(mbta_url, params={"filter[route]": route}, headers=mbta_headers)
    mbta_fields = []
    for vehicle in mbta_response.json()['data']:
        row = {
            'vehicle_id': vehicle['id'],
            'lat': vehicle['attributes']['latitude'],
            'lon': vehicle['attributes']['longitude'],
            'direction': vehicle['attributes']['direction_id'],
            'timestamp': vehicle['attributes']['updated_at'],
            'stop_sequence': vehicle['attributes']['current_stop_sequence'],
            'trip_id': vehicle['relationships']['trip']['data']['id'],
            'route_id': vehicle['relationships']['route']['data']['id']
        }
        mbta_fields.append(row)
    mbta_df = pd.DataFrame(mbta_fields)
    mbta_df['agency'] = 'MBTA'
    mbta_df['timestamp'] = pd.to_datetime(mbta_df['timestamp']).dt.tz_localize(None)
    mbta_dfs.append(mbta_df)

mbta_df = pd.concat(mbta_dfs, ignore_index=True)
mbta_df

,vehicle_id,lat,lon,direction,timestamp,stop_sequence,trip_id,route_id,agency
0,y1922,42.329830,-71.083710,0,2026-03-31 20:48:04,1,73601905,1,MBTA
1,y1875,42.336768,-71.077224,0,2026-03-31 20:48:23,8,73601895,1,MBTA
2,y1864,42.357648,-71.092876,1,2026-03-31 20:48:20,11,73602195,1,MBTA
3,y1849,42.340768,-71.081972,1,2026-03-31 20:48:16,16,73602191,1,MBTA
4,y1846,42.362598,-71.099434,0,2026-03-31 20:48:24,17,73601894,1,MBTA
5,y1729,42.373356,-71.117745,1,2026-03-31 20:48:18,1,73602194,1,MBTA
6,y1918,42.283650,-71.063910,1,2026-03-31 20:48:12,1,73601420,23,MBTA
7,y1910,42.308510,-71.083170,0,2026-03-31 20:48:08,16,73603918,23,MBTA
8,y1862,42.325546,-71.083475,0,2026-03-31 20:48:18,7,73603917,23,MBTA
9,y1833,42.331588,-71.094135,1,2026-03-31 20:48:23,29,73601418,23,MBTA
10,y1830,42.310966,-71.083198,1,2026-03-31 20:48:20,15,73601419,23,MBTA
11,y1825,42.336140,-71.088960,0,2026-03-31 20:48:14,1,73602675,23,MBTA
12,y1786,42.284610,-71.064070,1,2026-03-31 20:48:14,1,73601415,23,MBTA
13,y1271,42.321483,-71.081797,1,2026-03-31 20:48:21,27,73766556,28,MBTA
14,y1265,42.284553,-71.091286,1,2026-03-31 20:48:22,9,73766498,28,MBTA
15,y1260,42.332281,-71.071753,0,2026-03-31 20:48:04,1,73766422,28,MBTA
16,y1251,42.334240,-71.089940,1,2026-03-31 20:48:16,37,73766421,28,MBTA
17,y1224,42.298483,-71.086964,0,2026-03-31 20:48:22,20,73766442,28,MBTA
18,y1217,42.334340,-71.089690,1,2026-03-31 20:47:58,37,73766463,28,MBTA
19,y1215,42.276549,-71.093687,0,2026-03-31 20:48:22,29,73766462,28,MBTA
20,y1210,42.305711,-71.084787,0,2026-03-31 20:48:20,17,73766482,28,MBTA
21,y1209,42.310122,-71.083170,0,2026-03-31 20:48:15,15,73766430,28,MBTA
22,y1201,42.291503,-71.088930,1,2026-03-31 20:48:26,13,73766517,28,MBTA
23,y1268,42.341631,-71.086449,0,2026-03-31 20:48:20,5,73767435,39,MBTA
24,y1262,42.349944,-71.074822,0,2026-03-31 20:48:24,3,73767439,39,MBTA
25,y1257,42.322752,-71.112248,1,2026-03-31 20:48:25,10,73767438,39,MBTA
26,y1254,42.299700,-71.114220,1,2026-03-31 20:47:53,1,73767440,39,MBTA
27,y1219,42.330213,-71.060841,0,2026-03-31 20:48:21,1,73767441,39,MBTA
28,y1218,42.344969,-71.081903,1,2026-03-31 20:48:00,22,73767436,39,MBTA
29,y1216,42.350392,-71.075496,1,2026-03-31 20:48:26,25,73767432,39,MBTA
30,y3279,42.356458,-71.183179,0,2026-03-31 20:48:25,30,73584617,57,MBTA
31,y3256,42.348910,-71.097760,1,2026-03-31 20:47:44,34,73584786,57,MBTA
32,y3222,42.349140,-71.155044,1,2026-03-31 20:48:23,17,73584778,57,MBTA
33,y3213,42.350502,-71.166786,0,2026-03-31 20:48:20,22,73584784,57,MBTA
34,y3204,42.352495,-71.127027,1,2026-03-31 20:48:23,27,73584785,57,MBTA
35,y3200,42.351462,-71.118069,0,2026-03-31 20:48:20,7,73584787,57,MBTA
36,y1898,42.341230,-71.058040,0,2026-03-31 20:48:18,1,73604361,57,MBTA
37,y3285,42.358639,-71.126889,0,2026-03-31 20:48:23,26,73583901,66,MBTA
38,y3281,42.331504,-71.095364,1,2026-03-31 20:48:22,31,73584020,66,MBTA
39,y3269,42.350586,-71.131180,1,2026-03-31 20:48:24,15,73584021,66,MBTA
40,y3264,42.331936,-71.114342,0,2026-03-31 20:48:19,13,73583900,66,MBTA
41,y3257,42.373600,-71.118958,1,2026-03-31 20:48:17,1,73584019,66,MBTA
42,y3251,42.329140,-71.083920,0,2026-03-31 20:47:43,1,73583902,66,MBTA
43,y3219,42.358024,-71.126579,1,2026-03-31 20:48:18,9,73584022,66,MBTA
44,y3217,42.344195,-71.124822,0,2026-03-31 20:48:21,18,73583897,66,MBTA
45,y1916,42.341160,-71.058380,0,2026-03-31 20:48:19,1,73601900,66,MBTA
46,y1907,42.328980,-71.083950,0,2026-03-31 20:48:11,1,73601904,66,MBTA

### 3) MTA API
#### Bus Routes: B44, B46, B41, Bx12, M14A, M104A

In [60]:
MTA_KEY = '7027c575-3c63-477c-91d8-3d404472e8a0'

In [61]:
mta_url = "http://bustime.mta.info/api/siri/vehicle-monitoring.json"
mta_params = {
    "key": MTA_KEY,
    "LineRef": "MTA NYCT_B44"
}
requests.get(mta_url, params=mta_params)

In [62]:
mta_response = requests.get(mta_url, params=mta_params)
mta_response.json()

{'Siri': {'ServiceDelivery': {'ResponseTimestamp': '2026-03-31T20:48:28.930-04:00',
   'VehicleMonitoringDelivery': [{'VehicleActivity': [{'MonitoredVehicleJourney': {'LineRef': 'MTA NYCT_B44',
        'DirectionRef': '1',
        'FramedVehicleJourneyRef': {'DataFrameRef': '2026-03-31',
         'DatedVehicleJourneyRef': 'MTA NYCT_FB_A6-Weekday-SDon-123700_B44_335'},
        'JourneyPatternRef': 'MTA_B44O0126',
        'PublishedLineName': 'B44',
        'OperatorRef': 'MTA NYCT',
        'OriginRef': 'MTA_308704',
        'DestinationName': 'SHEEPSHEAD BAY KNAPP ST via NOSTRAND',
        'OriginAimedDepartureTime': '2026-03-31T20:37:00.000-04:00',
        'SituationRef': [{'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:22527'},
         {'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:15159'}],
        'Monitored': True,
        'VehicleLocation': {'Longitude': -73.953665, 'Latitude': 40.699878},
        'Bearing': 305.83765,
        'ProgressRate': 'noProgress',
        'ProgressStatus': 'layover',
        'BlockRef': 'MTA NYCT_FB_A6-Weekday-SDon_E_FB_34080_B44-311',
        'VehicleRef': 'MTA NYCT_7957',
        'MonitoredCall': {'AimedArrivalTime': '2026-03-31T20:37:00.000-04:00',
         'ExpectedArrivalTime': '2026-03-31T20:48:29.930-04:00',
         'AimedDepartureTime': '2026-03-31T20:37:00.000-04:00',
         'ExpectedDepartureTime': '2026-03-31T20:48:29.930-04:00',
         'Extensions': {'Distances': {'CallDistanceAlongRoute': 0.0,
           'PresentableDistance': 'at stop',
           'DistanceFromCall': 0.0,
           'StopsFromCall': 0},
          'VehicleFeatures': {'StrollerVehicle': False}},
         'StopPointRef': 'MTA_308704',
         'VisitNumber': 1,
         'StopPointName': 'LEE AV/WALLABOUT ST'},
        'OnwardCalls': {}},
       'RecordedAtTime': '2026-03-31T20:48:21.000-04:00'},
      {'MonitoredVehicleJourney': {'LineRef': 'MTA NYCT_B44',
        'DirectionRef': '0',
        'FramedVehicleJourneyRef': {'DataFrameRef': '2026-03-31',
         'DatedVehicleJourneyRef': 'MTA NYCT_FB_A6-Weekday-SDon-115300_B44_344'},
        'JourneyPatternRef': 'MTA_B44O0113',
        'PublishedLineName': 'B44',
        'OperatorRef': 'MTA NYCT',
        'OriginRef': 'MTA_303440',
        'DestinationName': 'FLUSHING AV via NOSTRAND',
        'OriginAimedDepartureTime': '2026-03-31T20:27:00.000-04:00',
        'SituationRef': [{'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:22527'},
         {'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:15159'}],
        'Monitored': True,
        'VehicleLocation': {'Longitude': -73.957008, 'Latitude': 40.698872},
        'Bearing': 101.753105,
        'ProgressRate': 'noProgress',
        'Occupancy': 'seatsAvailable',
        'ProgressStatus': 'layover',
        'BlockRef': 'MTA NYCT_FB_A6-Weekday-SDon_E_FB_56340_B44-345',
        'VehicleRef': 'MTA NYCT_7699',
        'OnwardCalls': {}},
       'RecordedAtTime': '2026-03-31T20:48:07.000-04:00'},
      {'MonitoredVehicleJourney': {'LineRef': 'MTA NYCT_B44',
        'DirectionRef': '0',
        'FramedVehicleJourneyRef': {'DataFrameRef': '2026-03-31',
         'DatedVehicleJourneyRef': 'MTA NYCT_FB_A6-Weekday-SDon-117200_B44_331'},
        'JourneyPatternRef': 'MTA_B44O0111',
        'PublishedLineName': 'B44',
        'OperatorRef': 'MTA NYCT',
        'OriginRef': 'MTA_308699',
        'DestinationName': 'FLUSHING AV via NOSTRAND',
        'OriginAimedDepartureTime': '2026-03-31T20:57:00.000-04:00',
        'SituationRef': [{'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:22527'},
         {'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:15159'}],
        'Monitored': True,
        'VehicleLocation': {'Longitude': -73.957008, 'Latitude': 40.698872},
        'Bearing': 101.753105,
        'ProgressRate': 'noProgress',
        'ProgressStatus': 'layover',
        'BlockRef': 'MTA NYCT_FB_A6-Weekday-SDon_E_FB_19440_B44-310',
        'VehicleRef': 'MTA NYCT_7323',
        'OnwardCalls': {}},
       'RecordedAtTime': '2026-03-31T20:48:13.000-04:00'},
      {'MonitoredVehicleJourney': {'LineRef': 'MTA NYCT_B44',
        'DirectionRef': '0',
        'FramedVehicleJourneyRef': {'DataFrameRef': '2026-03-31',
         'DatedVehicleJourneyRef': 'MTA NYCT_FB_A6-Weekday-SDon-121200_B44_345'},
        'JourneyPatternRef': 'MTA_B44O0111',
        'PublishedLineName': 'B44',
        'OperatorRef': 'MTA NYCT',
        'OriginRef': 'MTA_308699',
        'DestinationName': 'FLUSHING AV via NOSTRAND',
        'SituationRef': [{'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:22527'},
         {'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:15159'}],
        'Monitored': True,
        'VehicleLocation': {'Longitude': -73.947797, 'Latitude': 40.634265},
        'Bearing': 95.74627,
        'ProgressRate': 'normalProgress',
        'BlockRef': 'MTA NYCT_FB_A6-Weekday-SDon_E_FB_49920_B44-338',
        'VehicleRef': 'MTA NYCT_7330',
        'MonitoredCall': {'AimedArrivalTime': '2026-03-31T20:38:28.000-04:00',
         'ExpectedArrivalTime': '2026-03-31T20:48:29.930-04:00',
         'AimedDepartureTime': '2026-03-31T20:38:28.000-04:00',
         'ExpectedDepartureTime': '2026-03-31T20:48:29.930-04:00',
         'Extensions': {'Distances': {'CallDistanceAlongRoute': 6376.46,
           'PresentableDistance': 'at stop',
           'DistanceFromCall': 4.98,
           'StopsFromCall': 0},
          'VehicleFeatures': {'StrollerVehicle': False}},
         'StopPointRef': 'MTA_303381',
         'VisitNumber': 1,
         'StopPointName': 'NOSTRAND AV/GLENWOOD RD'},
        'OnwardCalls': {}},
       'RecordedAtTime': '2026-03-31T20:48:11.000-04:00'},
      {'MonitoredVehicleJourney': {'LineRef': 'MTA NYCT_B44',
        'DirectionRef': '1',
        'FramedVehicleJourneyRef': {'DataFrameRef': '2026-03-31',
         'DatedVehicleJourneyRef': 'MTA NYCT_FB_A6-Weekday-SDon-115700_B44_329'},
        'JourneyPatternRef': 'MTA_B44O0126',
        'PublishedLineName': 'B44',
        'OperatorRef': 'MTA NYCT',
        'OriginRef': 'MTA_308704',
        'DestinationName': 'SHEEPSHEAD BAY KNAPP ST via NOSTRAND',
        'SituationRef': [{'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:22527'},
         {'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:15159'}],
        'Monitored': True,
        'VehicleLocation': {'Longitude': -73.93218, 'Latitude': 40.585691},
        'Bearing': 343.07248,
        'ProgressRate': 'normalProgress',
        'BlockRef': 'MTA NYCT_FB_A6-Weekday-SDon_E_FB_21000_B44-315',
        'VehicleRef': 'MTA NYCT_7701',
        'MonitoredCall': {'AimedArrivalTime': '2026-03-31T20:27:42.000-04:00',
         'AimedDepartureTime': '2026-03-31T20:27:42.000-04:00',
         'Extensions': {'Distances': {'CallDistanceAlongRoute': 13470.9,
           'PresentableDistance': 'approaching',
           'DistanceFromCall': 51.41,
           'StopsFromCall': 0},
          'VehicleFeatures': {'StrollerVehicle': False}},
         'StopPointRef': 'MTA_308480',
         'VisitNumber': 1,
         'StopPointName': 'SHORE PKWY/BRIGHAM ST'},
        'OnwardCalls': {}},
       'RecordedAtTime': '2026-03-31T20:48:12.000-04:00'},
      {'MonitoredVehicleJourney': {'LineRef': 'MTA NYCT_B44',
        'DirectionRef': '1',
        'FramedVehicleJourneyRef': {'DataFrameRef': '2026-03-31',
         'DatedVehicleJourneyRef': 'MTA NYCT_FB_A6-Weekday-SDon-120000_B44_332'},
        'JourneyPatternRef': 'MTA_B44O0130',
        'PublishedLineName': 'B44',
        'OperatorRef': 'MTA NYCT',
        'OriginRef': 'MTA_308704',
        'DestinationName': 'AVENUE U via NOSTRAND',
        'SituationRef': [{'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:22527'},
         {'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:15159'}],
        'Monitored': True,
        'VehicleLocation': {'Longitude': -73.948523, 'Latitude': 40.641163},
        'Bearing': 276.23724,
        'ProgressRate': 'normalProgress',
        'Occupancy': 'seatsAvailable',
        'VehicleRef': 'MTA NYCT_7949',
        'MonitoredCall': {'AimedArrivalTime': '2026-03-31T20:42:00.000-04:00',
         'ExpectedArrivalTime': '2026-03-31T20:48:44.296-04:00',
         'AimedDepartureTime': '2026-03-31T20:42:00.000-04:00',
         'ExpectedDepartureTime': '2026-03-31T20:48:44.296-04:00',
         'Extensions': {'Distances': {'CallDistanceAlongRoute': 6630.35,
           'PresentableDistance': 'approaching',
           'DistanceFromCall': 57.25,
           'StopsFromCall': 0},
          'Capacities': {'EstimatedPassengerCount': 16,
           'EstimatedPassengerCapacity': 80,
           'EstimatedPassengerLoadFactor': 'manySeatsAvailable'},
          'VehicleFeatures': {'StrollerVehicle': False}},
         'StopPointRef': 'MTA_308712',
         'VisitNumber': 1,
         'StopPointName': 'NOSTRAND AV/AVENUE D'},
        'OnwardCalls': {}},
       'RecordedAtTime': '2026-03-31T20:48:27.474-04:00'},
      {'MonitoredVehicleJourney': {'LineRef': 'MTA NYCT_B44',
        'DirectionRef': '1',
        'FramedVehicleJourneyRef': {'DataFrameRef': '2026-03-31',
         'DatedVehicleJourneyRef': 'MTA NYCT_FB_A6-Weekday-SDon-120800_B44_339'},
        'JourneyPatternRef': 'MTA_B44O0126',
        'PublishedLineName': 'B44',
        'OperatorRef': 'MTA NYCT',
        'OriginRef': 'MTA_308704',
        'DestinationName': 'SHEEPSHEAD BAY KNAPP ST via NOSTRAND',
        'SituationRef': [{'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:22527'},
         {'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:15159'}],
        'Monitored': True,
        'VehicleLocation': {'Longitude': -73.948979, 'Latitude': 40.645319},
        'Bearing': 275.89124,
        'ProgressRate': 'normalProgress',
        'BlockRef': 'MTA NYCT_FB_A6-Weekday-SDon_E_FB_23580_B44-320',
        'VehicleRef': 'MTA NYCT_7314',
        'MonitoredCall': {'AimedArrivalTime': '2026-03-31T20:46:26.000-04:00',
         'ExpectedArrivalTime': '2026-03-31T20:48:29.930-04:00',
         'AimedDepartureTime': '2026-03-31T20:46:26.000-04:00',
         'ExpectedDepartureTime': '2026-03-31T20:48:29.930-04:00',
         'Extensions': {'Distances': {'CallDistanceAlongRoute': 6166.82,
           'PresentableDistance': 'approaching',
           'DistanceFromCall': 57.45,
           'StopsFromCall': 0},
          'VehicleFeatures': {'StrollerVehicle': False}},
         'StopPointRef': 'MTA_303475',
         'VisitNumber': 1,
         'StopPointName': 'NOSTRAND AV/BEVERLY RD'},
        'OnwardCalls': {}},
       'RecordedAtTime': '2026-03-31T20:48:06.000-04:00'},
      {'MonitoredVehicleJourney': {'LineRef': 'MTA NYCT_B44',
        'DirectionRef': '1',
        'FramedVehicleJourneyRef': {'DataFrameRef': '2026-03-31',
         'DatedVehicleJourneyRef': 'MTA NYCT_FB_A6-Weekday-SDon-117400_B44_340'},
        'JourneyPatternRef': 'MTA_B44O0126',
        'PublishedLineName': 'B44',
        'OperatorRef': 'MTA NYCT',
        'OriginRef': 'MTA_308704',
        'DestinationName': 'SHEEPSHEAD BAY KNAPP ST via NOSTRAND',
        'SituationRef': [{'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:22527'},
         {'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:15159'}],
        'Monitored': True,
        'VehicleLocation': {'Longitude': -73.939123, 'Latitude': 40.585935},
        'Bearing': 279.4623,
        'ProgressRate': 'normalProgress',
        'BlockRef': 'MTA NYCT_FB_A6-Weekday-SDon_E_FB_42480_B44-325',
        'VehicleRef': 'MTA NYCT_7015',
        'MonitoredCall': {'AimedArrivalTime': '2026-03-31T20:42:01.000-04:00',
         'ExpectedArrivalTime': '2026-03-31T20:48:29.930-04:00',
         'AimedDepartureTime': '2026-03-31T20:42:01.000-04:00',
         'ExpectedDepartureTime': '2026-03-31T20:48:29.930-04:00',
         'Extensions': {'Distances': {'CallDistanceAlongRoute': 12853.2,
           'PresentableDistance': 'approaching',
           'DistanceFromCall': 85.39,
           'StopsFromCall': 0},
          'VehicleFeatures': {'StrollerVehicle': True}},
         'StopPointRef': 'MTA_306898',
         'VisitNumber': 1,
         'StopPointName': 'SHORE PKWY/NOSTRAND AV'},
        'OnwardCalls': {}},
       'RecordedAtTime': '2026-03-31T20:48:12.000-04:00'},
      {'MonitoredVehicleJourney': {'LineRef': 'MTA NYCT_B44',
        'DirectionRef': '0',
        'FramedVehicleJourneyRef': {'DataFrameRef': '2026-03-31',
         'DatedVehicleJourneyRef': 'MTA NYCT_FB_A6-Weekday-SDon-119300_B44_333'},
        'JourneyPatternRef': 'MTA_B44O0113',
        'PublishedLineName': 'B44',
        'OperatorRef': 'MTA NYCT',
        'OriginRef': 'MTA_303440',
        'DestinationName': 'FLUSHING AV via NOSTRAND',
        'SituationRef': [{'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:22527'},
         {'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:15159'}],
        'Monitored': True,
        'VehicleLocation': {'Longitude': -73.955267, 'Latitude': 40.690152},
        'Bearing': 101.61149,
        'ProgressRate': 'normalProgress',
        'BlockRef': 'MTA NYCT_FB_A6-Weekday-SDon_E_FB_48240_B44-336',
        'VehicleRef': 'MTA NYCT_7617',
        'MonitoredCall': {'AimedArrivalTime': '2026-03-31T20:48:43.000-04:00',
         'ExpectedArrivalTime': '2026-03-31T20:48:45.426-04:00',
         'AimedDepartureTime': '2026-03-31T20:48:43.000-04:00',
         'ExpectedDepartureTime': '2026-03-31T20:48:45.426-04:00',
         'Extensions': {'Distances': {'CallDistanceAlongRoute': 10849.8,
           'PresentableDistance': 'approaching',
           'DistanceFromCall': 126.39,
           'StopsFromCall': 0},
          'VehicleFeatures': {'StrollerVehicle': False}},
         'StopPointRef': 'MTA_303418',
         'VisitNumber': 1,
         'StopPointName': 'BEDFORD AV/DE KALB AV'},
        'OnwardCalls': {}},
       'RecordedAtTime': '2026-03-31T20:48:04.000-04:00'},
      {'MonitoredVehicleJourney': {'LineRef': 'MTA NYCT_B44',
        'DirectionRef': '0',
        'FramedVehicleJourneyRef': {'DataFrameRef': '2026-03-31',
         'DatedVehicleJourneyRef': 'MTA NYCT_FB_A6-Weekday-SDon-123300_B44_341'},
        'JourneyPatternRef': 'MTA_B44O0111',
        'PublishedLineName': 'B44',
        'OperatorRef': 'MTA NYCT',
        'OriginRef': 'MTA_308699',
        'DestinationName': 'FLUSHING AV via NOSTRAND',
        'SituationRef': [{'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:22527'},
         {'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:15159'}],
        'Monitored': True,
        'VehicleLocation': {'Longitude': -73.944264, 'Latitude': 40.613248},
        'Bearing': 101.56744,
        'ProgressRate': 'normalProgress',
        'Occupancy': 'seatsAvailable',
        'BlockRef': 'MTA NYCT_FB_A6-Weekday-SDon_E_FB_15360_B44-303',
        'VehicleRef': 'MTA NYCT_7316',
        'MonitoredCall': {'AimedArrivalTime': '2026-03-31T20:49:01.000-04:00',
         'ExpectedArrivalTime': '2026-03-31T20:48:31.311-04:00',
         'AimedDepartureTime': '2026-03-31T20:49:01.000-04:00',
         'ExpectedDepartureTime': '2026-03-31T20:48:31.311-04:00',
         'Extensions': {'Distances': {'CallDistanceAlongRoute': 4147.12,
           'PresentableDistance': 'approaching',
           'DistanceFromCall': 132.79,
           'StopsFromCall': 0},
          'Capacities': {'EstimatedPassengerCount': 5,
           'EstimatedPassengerCapacity': 80,
           'EstimatedPassengerLoadFactor': 'manySeatsAvailable'},
          'VehicleFeatures': {'StrollerVehicle': False}},
         'StopPointRef': 'MTA_303372',
         'VisitNumber': 1,
         'StopPointName': 'NOSTRAND AV/MARINE PKWY'},
        'OnwardCalls': {}},
       'RecordedAtTime': '2026-03-31T20:48:05.000-04:00'},
      {'MonitoredVehicleJourney': {'LineRef': 'MTA NYCT_B44',
        'DirectionRef': '0',
        'FramedVehicleJourneyRef': {'DataFrameRef': '2026-03-31',
         'DatedVehicleJourneyRef': 'MTA NYCT_FB_A6-Weekday-SDon-119200_B44_343'},
        'JourneyPatternRef': 'MTA_B44O0111',
        'PublishedLineName': 'B44',
        'OperatorRef': 'MTA NYCT',
        'OriginRef': 'MTA_308699',
        'DestinationName': 'FLUSHING AV via NOSTRAND',
        'SituationRef': [{'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:22527'},
         {'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:15159'}],
        'Monitored': True,
        'VehicleLocation': {'Longitude': -73.952325, 'Latitude': 40.680533},
        'Bearing': 177.39743,
        'ProgressRate': 'normalProgress',
        'BlockRef': 'MTA NYCT_FB_A6-Weekday-SDon_E_FB_48840_B44-337',
        'VehicleRef': 'MTA NYCT_7327',
        'MonitoredCall': {'AimedArrivalTime': '2026-03-31T20:51:17.000-04:00',
         'ExpectedArrivalTime': '2026-03-31T20:49:19.002-04:00',
         'AimedDepartureTime': '2026-03-31T20:51:17.000-04:00',
         'ExpectedDepartureTime': '2026-03-31T20:49:19.002-04:00',
         'Extensions': {'Distances': {'CallDistanceAlongRoute': 12329.21,
           'PresentableDistance': 'approaching',
           'DistanceFromCall': 133.57,
           'StopsFromCall': 0},
          'VehicleFeatures': {'StrollerVehicle': False}},
         'StopPointRef': 'MTA_303411',
         'VisitNumber': 1,
         'StopPointName': 'BEDFORD AV/FULTON ST'},
        'OnwardCalls': {}},
       'RecordedAtTime': '2026-03-31T20:48:26.747-04:00'},
      {'MonitoredVehicleJourney': {'LineRef': 'MTA NYCT_B44',
        'DirectionRef': '0',
        'FramedVehicleJourneyRef': {'DataFrameRef': '2026-03-31',
         'DatedVehicleJourneyRef': 'MTA NYCT_FB_A6-Weekday-SDon-121300_B44_334'},
        'JourneyPatternRef': 'MTA_B44O0113',
        'PublishedLineName': 'B44',
        'OperatorRef': 'MTA NYCT',
        'OriginRef': 'MTA_303440',
        'DestinationName': 'FLUSHING AV via NOSTRAND',
        'SituationRef': [{'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:22527'},
         {'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:15159'}],
        'Monitored': True,
        'VehicleLocation': {'Longitude': -73.946937, 'Latitude': 40.653389},
        'Bearing': 95.710594,
        'ProgressRate': 'normalProgress',
        'BlockRef': 'MTA NYCT_FB_A6-Weekday-SDon_E_FB_23760_B44-321',
        'VehicleRef': 'MTA NYCT_7635',
        'MonitoredCall': {'AimedArrivalTime': '2026-03-31T20:42:08.000-04:00',
         'ExpectedArrivalTime': '2026-03-31T20:49:03.928-04:00',
         'AimedDepartureTime': '2026-03-31T20:42:08.000-04:00',
         'ExpectedDepartureTime': '2026-03-31T20:49:03.928-04:00',
         'Extensions': {'Distances': {'CallDistanceAlongRoute': 6235.4,
           'PresentableDistance': 'approaching',
           'DistanceFromCall': 139.73,
           'StopsFromCall': 0},
          'VehicleFeatures': {'StrollerVehicle': False}},
         'StopPointRef': 'MTA_303392',
         'VisitNumber': 1,
         'StopPointName': 'NEW YORK AV/LENOX RD'},
        'OnwardCalls': {}},
       'RecordedAtTime': '2026-03-31T20:48:13.000-04:00'},
      {'MonitoredVehicleJourney': {'LineRef': 'MTA NYCT_B44',
        'DirectionRef': '1',
        'FramedVehicleJourneyRef': {'DataFrameRef': '2026-03-31',
         'DatedVehicleJourneyRef': 'MTA NYCT_FB_A6-Weekday-SDon-121700_B44_336'},
        'JourneyPatternRef': 'MTA_B44O0126',
        'PublishedLineName': 'B44',
        'OperatorRef': 'MTA NYCT',
        'OriginRef': 'MTA_308704',
        'DestinationName': 'SHEEPSHEAD BAY KNAPP ST via NOSTRAND',
        'SituationRef': [{'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:22527'},
         {'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:15159'}],
        'Monitored': True,
        'VehicleLocation': {'Longitude': -73.95063, 'Latitude': 40.668242},
        'Bearing': 264.35175,
        'ProgressRate': 'normalProgress',
        'Occupancy': 'seatsAvailable',
        'BlockRef': 'MTA NYCT_FB_A6-Weekday-SDon_E_FB_55440_B44-319',
        'VehicleRef': 'MTA NYCT_7615',
        'MonitoredCall': {'AimedArrivalTime': '2026-03-31T20:39:40.000-04:00',
         'ExpectedArrivalTime': '2026-03-31T20:49:09.148-04:00',
         'AimedDepartureTime': '2026-03-31T20:39:40.000-04:00',
         'ExpectedDepartureTime': '2026-03-31T20:49:09.148-04:00',

#### Fields Used
- `VehicleRef` →  `"MTA NYCT_"` prefix
- `VehicleLocation.Latitude`, `VehicleLocation.Longitude` 
- `DirectionRef` → direction (comes as string 0/1)
- `RecordedAtTime` → timestamp
- `LineRef` → route_id (strip `"MTA NYCT_"` prefix)
- `MonitoredCall.Extensions.Distances.CallDistanceAlongRoute` → stop_sequence
- `MonitoredCall.ExpectedArrivalTime` - `MonitoredCall.AimedArrivalTime` → used to calc deviation

In [63]:
mta_vehicles = mta_response.json()['Siri']['ServiceDelivery']['VehicleMonitoringDelivery'][0]['VehicleActivity']
mta_vehicles

[{'MonitoredVehicleJourney': {'LineRef': 'MTA NYCT_B44',
   'DirectionRef': '1',
   'FramedVehicleJourneyRef': {'DataFrameRef': '2026-03-31',
    'DatedVehicleJourneyRef': 'MTA NYCT_FB_A6-Weekday-SDon-123700_B44_335'},
   'JourneyPatternRef': 'MTA_B44O0126',
   'PublishedLineName': 'B44',
   'OperatorRef': 'MTA NYCT',
   'OriginRef': 'MTA_308704',
   'DestinationName': 'SHEEPSHEAD BAY KNAPP ST via NOSTRAND',
   'OriginAimedDepartureTime': '2026-03-31T20:37:00.000-04:00',
   'SituationRef': [{'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:22527'},
    {'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:15159'}],
   'Monitored': True,
   'VehicleLocation': {'Longitude': -73.953665, 'Latitude': 40.699878},
   'Bearing': 305.83765,
   'ProgressRate': 'noProgress',
   'ProgressStatus': 'layover',
   'BlockRef': 'MTA NYCT_FB_A6-Weekday-SDon_E_FB_34080_B44-311',
   'VehicleRef': 'MTA NYCT_7957',
   'MonitoredCall': {'AimedArrivalTime': '2026-03-31T20:37:00.000-04:00',
    'ExpectedArrivalTime': '2026-03-31T20:48:29.930-04:00',
    'AimedDepartureTime': '2026-03-31T20:37:00.000-04:00',
    'ExpectedDepartureTime': '2026-03-31T20:48:29.930-04:00',
    'Extensions': {'Distances': {'CallDistanceAlongRoute': 0.0,
      'PresentableDistance': 'at stop',
      'DistanceFromCall': 0.0,
      'StopsFromCall': 0},
     'VehicleFeatures': {'StrollerVehicle': False}},
    'StopPointRef': 'MTA_308704',
    'VisitNumber': 1,
    'StopPointName': 'LEE AV/WALLABOUT ST'},
   'OnwardCalls': {}},
  'RecordedAtTime': '2026-03-31T20:48:21.000-04:00'},
 {'MonitoredVehicleJourney': {'LineRef': 'MTA NYCT_B44',
   'DirectionRef': '0',
   'FramedVehicleJourneyRef': {'DataFrameRef': '2026-03-31',
    'DatedVehicleJourneyRef': 'MTA NYCT_FB_A6-Weekday-SDon-115300_B44_344'},
   'JourneyPatternRef': 'MTA_B44O0113',
   'PublishedLineName': 'B44',
   'OperatorRef': 'MTA NYCT',
   'OriginRef': 'MTA_303440',
   'DestinationName': 'FLUSHING AV via NOSTRAND',
   'OriginAimedDepartureTime': '2026-03-31T20:27:00.000-04:00',
   'SituationRef': [{'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:22527'},
    {'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:15159'}],
   'Monitored': True,
   'VehicleLocation': {'Longitude': -73.957008, 'Latitude': 40.698872},
   'Bearing': 101.753105,
   'ProgressRate': 'noProgress',
   'Occupancy': 'seatsAvailable',
   'ProgressStatus': 'layover',
   'BlockRef': 'MTA NYCT_FB_A6-Weekday-SDon_E_FB_56340_B44-345',
   'VehicleRef': 'MTA NYCT_7699',
   'OnwardCalls': {}},
  'RecordedAtTime': '2026-03-31T20:48:07.000-04:00'},
 {'MonitoredVehicleJourney': {'LineRef': 'MTA NYCT_B44',
   'DirectionRef': '0',
   'FramedVehicleJourneyRef': {'DataFrameRef': '2026-03-31',
    'DatedVehicleJourneyRef': 'MTA NYCT_FB_A6-Weekday-SDon-117200_B44_331'},
   'JourneyPatternRef': 'MTA_B44O0111',
   'PublishedLineName': 'B44',
   'OperatorRef': 'MTA NYCT',
   'OriginRef': 'MTA_308699',
   'DestinationName': 'FLUSHING AV via NOSTRAND',
   'OriginAimedDepartureTime': '2026-03-31T20:57:00.000-04:00',
   'SituationRef': [{'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:22527'},
    {'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:15159'}],
   'Monitored': True,
   'VehicleLocation': {'Longitude': -73.957008, 'Latitude': 40.698872},
   'Bearing': 101.753105,
   'ProgressRate': 'noProgress',
   'ProgressStatus': 'layover',
   'BlockRef': 'MTA NYCT_FB_A6-Weekday-SDon_E_FB_19440_B44-310',
   'VehicleRef': 'MTA NYCT_7323',
   'OnwardCalls': {}},
  'RecordedAtTime': '2026-03-31T20:48:13.000-04:00'},
 {'MonitoredVehicleJourney': {'LineRef': 'MTA NYCT_B44',
   'DirectionRef': '0',
   'FramedVehicleJourneyRef': {'DataFrameRef': '2026-03-31',
    'DatedVehicleJourneyRef': 'MTA NYCT_FB_A6-Weekday-SDon-121200_B44_345'},
   'JourneyPatternRef': 'MTA_B44O0111',
   'PublishedLineName': 'B44',
   'OperatorRef': 'MTA NYCT',
   'OriginRef': 'MTA_308699',
   'DestinationName': 'FLUSHING AV via NOSTRAND',
   'SituationRef': [{'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:22527'},
    {'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:15159'}],
   'Monitored': True,
   'VehicleLocation': {'Longitude': -73.947797, 'Latitude': 40.634265},
   'Bearing': 95.74627,
   'ProgressRate': 'normalProgress',
   'BlockRef': 'MTA NYCT_FB_A6-Weekday-SDon_E_FB_49920_B44-338',
   'VehicleRef': 'MTA NYCT_7330',
   'MonitoredCall': {'AimedArrivalTime': '2026-03-31T20:38:28.000-04:00',
    'ExpectedArrivalTime': '2026-03-31T20:48:29.930-04:00',
    'AimedDepartureTime': '2026-03-31T20:38:28.000-04:00',
    'ExpectedDepartureTime': '2026-03-31T20:48:29.930-04:00',
    'Extensions': {'Distances': {'CallDistanceAlongRoute': 6376.46,
      'PresentableDistance': 'at stop',
      'DistanceFromCall': 4.98,
      'StopsFromCall': 0},
     'VehicleFeatures': {'StrollerVehicle': False}},
    'StopPointRef': 'MTA_303381',
    'VisitNumber': 1,
    'StopPointName': 'NOSTRAND AV/GLENWOOD RD'},
   'OnwardCalls': {}},
  'RecordedAtTime': '2026-03-31T20:48:11.000-04:00'},
 {'MonitoredVehicleJourney': {'LineRef': 'MTA NYCT_B44',
   'DirectionRef': '1',
   'FramedVehicleJourneyRef': {'DataFrameRef': '2026-03-31',
    'DatedVehicleJourneyRef': 'MTA NYCT_FB_A6-Weekday-SDon-115700_B44_329'},
   'JourneyPatternRef': 'MTA_B44O0126',
   'PublishedLineName': 'B44',
   'OperatorRef': 'MTA NYCT',
   'OriginRef': 'MTA_308704',
   'DestinationName': 'SHEEPSHEAD BAY KNAPP ST via NOSTRAND',
   'SituationRef': [{'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:22527'},
    {'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:15159'}],
   'Monitored': True,
   'VehicleLocation': {'Longitude': -73.93218, 'Latitude': 40.585691},
   'Bearing': 343.07248,
   'ProgressRate': 'normalProgress',
   'BlockRef': 'MTA NYCT_FB_A6-Weekday-SDon_E_FB_21000_B44-315',
   'VehicleRef': 'MTA NYCT_7701',
   'MonitoredCall': {'AimedArrivalTime': '2026-03-31T20:27:42.000-04:00',
    'AimedDepartureTime': '2026-03-31T20:27:42.000-04:00',
    'Extensions': {'Distances': {'CallDistanceAlongRoute': 13470.9,
      'PresentableDistance': 'approaching',
      'DistanceFromCall': 51.41,
      'StopsFromCall': 0},
     'VehicleFeatures': {'StrollerVehicle': False}},
    'StopPointRef': 'MTA_308480',
    'VisitNumber': 1,
    'StopPointName': 'SHORE PKWY/BRIGHAM ST'},
   'OnwardCalls': {}},
  'RecordedAtTime': '2026-03-31T20:48:12.000-04:00'},
 {'MonitoredVehicleJourney': {'LineRef': 'MTA NYCT_B44',
   'DirectionRef': '1',
   'FramedVehicleJourneyRef': {'DataFrameRef': '2026-03-31',
    'DatedVehicleJourneyRef': 'MTA NYCT_FB_A6-Weekday-SDon-120000_B44_332'},
   'JourneyPatternRef': 'MTA_B44O0130',
   'PublishedLineName': 'B44',
   'OperatorRef': 'MTA NYCT',
   'OriginRef': 'MTA_308704',
   'DestinationName': 'AVENUE U via NOSTRAND',
   'SituationRef': [{'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:22527'},
    {'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:15159'}],
   'Monitored': True,
   'VehicleLocation': {'Longitude': -73.948523, 'Latitude': 40.641163},
   'Bearing': 276.23724,
   'ProgressRate': 'normalProgress',
   'Occupancy': 'seatsAvailable',
   'VehicleRef': 'MTA NYCT_7949',
   'MonitoredCall': {'AimedArrivalTime': '2026-03-31T20:42:00.000-04:00',
    'ExpectedArrivalTime': '2026-03-31T20:48:44.296-04:00',
    'AimedDepartureTime': '2026-03-31T20:42:00.000-04:00',
    'ExpectedDepartureTime': '2026-03-31T20:48:44.296-04:00',
    'Extensions': {'Distances': {'CallDistanceAlongRoute': 6630.35,
      'PresentableDistance': 'approaching',
      'DistanceFromCall': 57.25,
      'StopsFromCall': 0},
     'Capacities': {'EstimatedPassengerCount': 16,
      'EstimatedPassengerCapacity': 80,
      'EstimatedPassengerLoadFactor': 'manySeatsAvailable'},
     'VehicleFeatures': {'StrollerVehicle': False}},
    'StopPointRef': 'MTA_308712',
    'VisitNumber': 1,
    'StopPointName': 'NOSTRAND AV/AVENUE D'},
   'OnwardCalls': {}},
  'RecordedAtTime': '2026-03-31T20:48:27.474-04:00'},
 {'MonitoredVehicleJourney': {'LineRef': 'MTA NYCT_B44',
   'DirectionRef': '1',
   'FramedVehicleJourneyRef': {'DataFrameRef': '2026-03-31',
    'DatedVehicleJourneyRef': 'MTA NYCT_FB_A6-Weekday-SDon-120800_B44_339'},
   'JourneyPatternRef': 'MTA_B44O0126',
   'PublishedLineName': 'B44',
   'OperatorRef': 'MTA NYCT',
   'OriginRef': 'MTA_308704',
   'DestinationName': 'SHEEPSHEAD BAY KNAPP ST via NOSTRAND',
   'SituationRef': [{'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:22527'},
    {'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:15159'}],
   'Monitored': True,
   'VehicleLocation': {'Longitude': -73.948979, 'Latitude': 40.645319},
   'Bearing': 275.89124,
   'ProgressRate': 'normalProgress',
   'BlockRef': 'MTA NYCT_FB_A6-Weekday-SDon_E_FB_23580_B44-320',
   'VehicleRef': 'MTA NYCT_7314',
   'MonitoredCall': {'AimedArrivalTime': '2026-03-31T20:46:26.000-04:00',
    'ExpectedArrivalTime': '2026-03-31T20:48:29.930-04:00',
    'AimedDepartureTime': '2026-03-31T20:46:26.000-04:00',
    'ExpectedDepartureTime': '2026-03-31T20:48:29.930-04:00',
    'Extensions': {'Distances': {'CallDistanceAlongRoute': 6166.82,
      'PresentableDistance': 'approaching',
      'DistanceFromCall': 57.45,
      'StopsFromCall': 0},
     'VehicleFeatures': {'StrollerVehicle': False}},
    'StopPointRef': 'MTA_303475',
    'VisitNumber': 1,
    'StopPointName': 'NOSTRAND AV/BEVERLY RD'},
   'OnwardCalls': {}},
  'RecordedAtTime': '2026-03-31T20:48:06.000-04:00'},
 {'MonitoredVehicleJourney': {'LineRef': 'MTA NYCT_B44',
   'DirectionRef': '1',
   'FramedVehicleJourneyRef': {'DataFrameRef': '2026-03-31',
    'DatedVehicleJourneyRef': 'MTA NYCT_FB_A6-Weekday-SDon-117400_B44_340'},
   'JourneyPatternRef': 'MTA_B44O0126',
   'PublishedLineName': 'B44',
   'OperatorRef': 'MTA NYCT',
   'OriginRef': 'MTA_308704',
   'DestinationName': 'SHEEPSHEAD BAY KNAPP ST via NOSTRAND',
   'SituationRef': [{'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:22527'},
    {'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:15159'}],
   'Monitored': True,
   'VehicleLocation': {'Longitude': -73.939123, 'Latitude': 40.585935},
   'Bearing': 279.4623,
   'ProgressRate': 'normalProgress',
   'BlockRef': 'MTA NYCT_FB_A6-Weekday-SDon_E_FB_42480_B44-325',
   'VehicleRef': 'MTA NYCT_7015',
   'MonitoredCall': {'AimedArrivalTime': '2026-03-31T20:42:01.000-04:00',
    'ExpectedArrivalTime': '2026-03-31T20:48:29.930-04:00',
    'AimedDepartureTime': '2026-03-31T20:42:01.000-04:00',
    'ExpectedDepartureTime': '2026-03-31T20:48:29.930-04:00',
    'Extensions': {'Distances': {'CallDistanceAlongRoute': 12853.2,
      'PresentableDistance': 'approaching',
      'DistanceFromCall': 85.39,
      'StopsFromCall': 0},
     'VehicleFeatures': {'StrollerVehicle': True}},
    'StopPointRef': 'MTA_306898',
    'VisitNumber': 1,
    'StopPointName': 'SHORE PKWY/NOSTRAND AV'},
   'OnwardCalls': {}},
  'RecordedAtTime': '2026-03-31T20:48:12.000-04:00'},
 {'MonitoredVehicleJourney': {'LineRef': 'MTA NYCT_B44',
   'DirectionRef': '0',
   'FramedVehicleJourneyRef': {'DataFrameRef': '2026-03-31',
    'DatedVehicleJourneyRef': 'MTA NYCT_FB_A6-Weekday-SDon-119300_B44_333'},
   'JourneyPatternRef': 'MTA_B44O0113',
   'PublishedLineName': 'B44',
   'OperatorRef': 'MTA NYCT',
   'OriginRef': 'MTA_303440',
   'DestinationName': 'FLUSHING AV via NOSTRAND',
   'SituationRef': [{'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:22527'},
    {'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:15159'}],
   'Monitored': True,
   'VehicleLocation': {'Longitude': -73.955267, 'Latitude': 40.690152},
   'Bearing': 101.61149,
   'ProgressRate': 'normalProgress',
   'BlockRef': 'MTA NYCT_FB_A6-Weekday-SDon_E_FB_48240_B44-336',
   'VehicleRef': 'MTA NYCT_7617',
   'MonitoredCall': {'AimedArrivalTime': '2026-03-31T20:48:43.000-04:00',
    'ExpectedArrivalTime': '2026-03-31T20:48:45.426-04:00',
    'AimedDepartureTime': '2026-03-31T20:48:43.000-04:00',
    'ExpectedDepartureTime': '2026-03-31T20:48:45.426-04:00',
    'Extensions': {'Distances': {'CallDistanceAlongRoute': 10849.8,
      'PresentableDistance': 'approaching',
      'DistanceFromCall': 126.39,
      'StopsFromCall': 0},
     'VehicleFeatures': {'StrollerVehicle': False}},
    'StopPointRef': 'MTA_303418',
    'VisitNumber': 1,
    'StopPointName': 'BEDFORD AV/DE KALB AV'},
   'OnwardCalls': {}},
  'RecordedAtTime': '2026-03-31T20:48:04.000-04:00'},
 {'MonitoredVehicleJourney': {'LineRef': 'MTA NYCT_B44',
   'DirectionRef': '0',
   'FramedVehicleJourneyRef': {'DataFrameRef': '2026-03-31',
    'DatedVehicleJourneyRef': 'MTA NYCT_FB_A6-Weekday-SDon-123300_B44_341'},
   'JourneyPatternRef': 'MTA_B44O0111',
   'PublishedLineName': 'B44',
   'OperatorRef': 'MTA NYCT',
   'OriginRef': 'MTA_308699',
   'DestinationName': 'FLUSHING AV via NOSTRAND',
   'SituationRef': [{'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:22527'},
    {'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:15159'}],
   'Monitored': True,
   'VehicleLocation': {'Longitude': -73.944264, 'Latitude': 40.613248},
   'Bearing': 101.56744,
   'ProgressRate': 'normalProgress',
   'Occupancy': 'seatsAvailable',
   'BlockRef': 'MTA NYCT_FB_A6-Weekday-SDon_E_FB_15360_B44-303',
   'VehicleRef': 'MTA NYCT_7316',
   'MonitoredCall': {'AimedArrivalTime': '2026-03-31T20:49:01.000-04:00',
    'ExpectedArrivalTime': '2026-03-31T20:48:31.311-04:00',
    'AimedDepartureTime': '2026-03-31T20:49:01.000-04:00',
    'ExpectedDepartureTime': '2026-03-31T20:48:31.311-04:00',
    'Extensions': {'Distances': {'CallDistanceAlongRoute': 4147.12,
      'PresentableDistance': 'approaching',
      'DistanceFromCall': 132.79,
      'StopsFromCall': 0},
     'Capacities': {'EstimatedPassengerCount': 5,
      'EstimatedPassengerCapacity': 80,
      'EstimatedPassengerLoadFactor': 'manySeatsAvailable'},
     'VehicleFeatures': {'StrollerVehicle': False}},
    'StopPointRef': 'MTA_303372',
    'VisitNumber': 1,
    'StopPointName': 'NOSTRAND AV/MARINE PKWY'},
   'OnwardCalls': {}},
  'RecordedAtTime': '2026-03-31T20:48:05.000-04:00'},
 {'MonitoredVehicleJourney': {'LineRef': 'MTA NYCT_B44',
   'DirectionRef': '0',
   'FramedVehicleJourneyRef': {'DataFrameRef': '2026-03-31',
    'DatedVehicleJourneyRef': 'MTA NYCT_FB_A6-Weekday-SDon-119200_B44_343'},
   'JourneyPatternRef': 'MTA_B44O0111',
   'PublishedLineName': 'B44',
   'OperatorRef': 'MTA NYCT',
   'OriginRef': 'MTA_308699',
   'DestinationName': 'FLUSHING AV via NOSTRAND',
   'SituationRef': [{'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:22527'},
    {'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:15159'}],
   'Monitored': True,
   'VehicleLocation': {'Longitude': -73.952325, 'Latitude': 40.680533},
   'Bearing': 177.39743,
   'ProgressRate': 'normalProgress',
   'BlockRef': 'MTA NYCT_FB_A6-Weekday-SDon_E_FB_48840_B44-337',
   'VehicleRef': 'MTA NYCT_7327',
   'MonitoredCall': {'AimedArrivalTime': '2026-03-31T20:51:17.000-04:00',
    'ExpectedArrivalTime': '2026-03-31T20:49:19.002-04:00',
    'AimedDepartureTime': '2026-03-31T20:51:17.000-04:00',
    'ExpectedDepartureTime': '2026-03-31T20:49:19.002-04:00',
    'Extensions': {'Distances': {'CallDistanceAlongRoute': 12329.21,
      'PresentableDistance': 'approaching',
      'DistanceFromCall': 133.57,
      'StopsFromCall': 0},
     'VehicleFeatures': {'StrollerVehicle': False}},
    'StopPointRef': 'MTA_303411',
    'VisitNumber': 1,
    'StopPointName': 'BEDFORD AV/FULTON ST'},
   'OnwardCalls': {}},
  'RecordedAtTime': '2026-03-31T20:48:26.747-04:00'},
 {'MonitoredVehicleJourney': {'LineRef': 'MTA NYCT_B44',
   'DirectionRef': '0',
   'FramedVehicleJourneyRef': {'DataFrameRef': '2026-03-31',
    'DatedVehicleJourneyRef': 'MTA NYCT_FB_A6-Weekday-SDon-121300_B44_334'},
   'JourneyPatternRef': 'MTA_B44O0113',
   'PublishedLineName': 'B44',
   'OperatorRef': 'MTA NYCT',
   'OriginRef': 'MTA_303440',
   'DestinationName': 'FLUSHING AV via NOSTRAND',
   'SituationRef': [{'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:22527'},
    {'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:15159'}],
   'Monitored': True,
   'VehicleLocation': {'Longitude': -73.946937, 'Latitude': 40.653389},
   'Bearing': 95.710594,
   'ProgressRate': 'normalProgress',
   'BlockRef': 'MTA NYCT_FB_A6-Weekday-SDon_E_FB_23760_B44-321',
   'VehicleRef': 'MTA NYCT_7635',
   'MonitoredCall': {'AimedArrivalTime': '2026-03-31T20:42:08.000-04:00',
    'ExpectedArrivalTime': '2026-03-31T20:49:03.928-04:00',
    'AimedDepartureTime': '2026-03-31T20:42:08.000-04:00',
    'ExpectedDepartureTime': '2026-03-31T20:49:03.928-04:00',
    'Extensions': {'Distances': {'CallDistanceAlongRoute': 6235.4,
      'PresentableDistance': 'approaching',
      'DistanceFromCall': 139.73,
      'StopsFromCall': 0},
     'VehicleFeatures': {'StrollerVehicle': False}},
    'StopPointRef': 'MTA_303392',
    'VisitNumber': 1,
    'StopPointName': 'NEW YORK AV/LENOX RD'},
   'OnwardCalls': {}},
  'RecordedAtTime': '2026-03-31T20:48:13.000-04:00'},
 {'MonitoredVehicleJourney': {'LineRef': 'MTA NYCT_B44',
   'DirectionRef': '1',
   'FramedVehicleJourneyRef': {'DataFrameRef': '2026-03-31',
    'DatedVehicleJourneyRef': 'MTA NYCT_FB_A6-Weekday-SDon-121700_B44_336'},
   'JourneyPatternRef': 'MTA_B44O0126',
   'PublishedLineName': 'B44',
   'OperatorRef': 'MTA NYCT',
   'OriginRef': 'MTA_308704',
   'DestinationName': 'SHEEPSHEAD BAY KNAPP ST via NOSTRAND',
   'SituationRef': [{'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:22527'},
    {'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:15159'}],
   'Monitored': True,
   'VehicleLocation': {'Longitude': -73.95063, 'Latitude': 40.668242},
   'Bearing': 264.35175,
   'ProgressRate': 'normalProgress',
   'Occupancy': 'seatsAvailable',
   'BlockRef': 'MTA NYCT_FB_A6-Weekday-SDon_E_FB_55440_B44-319',
   'VehicleRef': 'MTA NYCT_7615',
   'MonitoredCall': {'AimedArrivalTime': '2026-03-31T20:39:40.000-04:00',
    'ExpectedArrivalTime': '2026-03-31T20:49:09.148-04:00',
    'AimedDepartureTime': '2026-03-31T20:39:40.000-04:00',
    'ExpectedDepartureTime': '2026-03-31T20:49:09.148-04:00',
    'Extensions': {'Distances': {'CallDistanceAlongRoute': 3705.61,
      'PresentableDistance': '< 1 stop away',
      'DistanceFromCall': 153.9,
      'StopsFromCall': 0},
     'Capacities': {'EstimatedPassengerCount': 18,
      'EstimatedPassengerCapacity': 80,
      'EstimatedPassengerLoadFactor': 'manySeatsAvailable'},
     'VehicleFeatures': {'StrollerVehicle': False}},
    'StopPointRef': 'MTA_303461',
    'VisitNumber': 1,
    'StopPointName': 'NOSTRAND AV/CARROLL ST'},
   'OnwardCalls': {}},
  'RecordedAtTime': '2026-03-31T20:48:13.000-04:00'},
 {'MonitoredVehicleJourney': {'LineRef': 'MTA NYCT_B44',
   'DirectionRef': '0',
   'FramedVehicleJourneyRef': {'DataFrameRef': '2026-03-31',
    'DatedVehicleJourneyRef': 'MTA NYCT_FB_A6-Weekday-SDon-123300_B44_337'},
   'JourneyPatternRef': 'MTA_B44O0113',
   'PublishedLineName': 'B44',
   'OperatorRef': 'MTA NYCT',
   'OriginRef': 'MTA_303440',
   'DestinationName': 'FLUSHING AV via NOSTRAND',
   'SituationRef': [{'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:22527'},
    {'SituationSimpleRef': 'MTA NYCT_lmm:planned_work:15159'}],
   'Monitored': True,
   'VehicleLocation': {'Longitude': -73.946928, 'Latitude': 40.627145},
   'Bearing': 100.47241,
   'ProgressRate': 'normalProgress',
   'Occupancy': 'seatsAvailable',
   'BlockRef': 'MTA NYCT_FB_A6-Weekday-SDon_E_FB_51480_B44-341',
   'VehicleRef': 'MTA NYCT_7944',
   'MonitoredCall': {'AimedArrivalTime': '2026-03-31T20:45:44.000-04:00',
    'ExpectedArrivalTime': '2026-03-31T20:49:11.275-04:00',
    'AimedDepartureTime': '2026-03-31T20:45:44.000-04:00',
    'ExpectedDepartureTime': '2026-03-31T20:49:11.275-04:00',
    'Extensions': {'Distances': {'CallDistanceAlongRoute': 3205.86,
      'PresentableDistance': '< 1 stop away',
      'DistanceFromCall': 262.08,
      'StopsFromCall': 0},
     'Capacities': {'EstimatedPassengerCount': 6,
      'EstimatedPassengerCapacity': 80,
      'EstimatedPassengerLoadFactor': 'manySeatsAvailable'},
     'VehicleFeatures': {'StrollerVehicle': False}},

In [64]:
mta_routes = ['B44', 'B46', 'B41', 'Bx12', 'M14A', 'M104']
mta_dfs = []

for route in mta_routes:
    mta_params = {"key": MTA_KEY, "LineRef": f"MTA NYCT_{route}"} #This needs to be in the loop not outside
    response = requests.get(mta_url, params=mta_params)
    delivery = response.json()['Siri']['ServiceDelivery']['VehicleMonitoringDelivery'][0]
    mta_vehicles = delivery.get('VehicleActivity', [])  # creating an empty list if no active vehicles (this caused loop to not work)
    
    mta_rows = []
    for vehicle in mta_vehicles:
        mvj = vehicle['MonitoredVehicleJourney']  # the path to data
        if 'MonitoredCall' not in mvj:  # skip buses in layover (this also caused loop to not work)
            continue
        mc = mvj['MonitoredCall']  # the path to data

        if 'ExpectedArrivalTime' not in mc:  # skip vehicles with no prediction (Dropping, won't be able to calc dev)
            continue
        
         # parse both times so it can be subtracted to get dev
        aimed = pd.to_datetime(mc['AimedArrivalTime'])
        expected = pd.to_datetime(mc['ExpectedArrivalTime'])
        
        row = {
            'vehicle_id': mvj['VehicleRef'].replace('MTA NYCT_', ''),  # removing prefix
            'lat': mvj['VehicleLocation']['Latitude'],
            'lon': mvj['VehicleLocation']['Longitude'],
            'direction': int(mvj['DirectionRef']),  # making the string "0"/"1" a int
            'timestamp': pd.to_datetime(vehicle['RecordedAtTime']),
            'route_id': mvj['LineRef'].replace('MTA NYCT_', ''),  # removing prefix
            'call_distance': mc['Extensions']['Distances']['CallDistanceAlongRoute'],  # stop_sequence equivalent
            'deviation_min': (expected - aimed).total_seconds() / 60  # positive = late, negative = early
        }
        mta_rows.append(row)
    
    df = pd.DataFrame(mta_rows)
    if df.empty:  # skip if no valid vehicles for this route
        continue
    df['agency'] = 'MTA'
    df['timestamp'] = df['timestamp'].dt.tz_localize(None)  # making timezone to match WMATA/MBTA
    mta_dfs.append(df)

mta_df = pd.concat(mta_dfs, ignore_index=True)
mta_df

,vehicle_id,lat,lon,direction,timestamp,route_id,call_distance,deviation_min,agency
0,7957,40.699878,-73.953665,1,2026-03-31 20:48:21.000,B44,0.00,11.502633,MTA
1,7314,40.645319,-73.948979,1,2026-03-31 20:48:06.000,B44,6166.82,2.069300,MTA
2,7330,40.634265,-73.947797,0,2026-03-31 20:48:11.000,B44,6376.46,10.035967,MTA
3,7949,40.641163,-73.948523,1,2026-03-31 20:48:27.474,B44,6630.35,6.738267,MTA
4,7015,40.585935,-73.939123,1,2026-03-31 20:48:12.000,B44,12853.20,6.485967,MTA
5,7617,40.690152,-73.955267,0,2026-03-31 20:48:04.000,B44,10849.80,0.040433,MTA
6,7316,40.613248,-73.944264,0,2026-03-31 20:48:05.000,B44,4147.12,-0.494817,MTA
7,7327,40.680533,-73.952325,0,2026-03-31 20:48:26.747,B44,12329.21,-1.966633,MTA
8,7635,40.653389,-73.946937,0,2026-03-31 20:48:13.000,B44,6235.40,6.932133,MTA
9,7615,40.668242,-73.950630,1,2026-03-31 20:48:13.000,B44,3705.61,9.485800,MTA
10,7944,40.627145,-73.946928,0,2026-03-31 20:48:13.000,B44,3205.86,3.454583,MTA
11,7356,40.699638,-73.953492,1,2026-03-31 20:47:59.000,B44,341.80,0.145283,MTA
12,7646,40.616391,-73.944914,1,2026-03-31 20:48:17.000,B44,9878.81,42.803450,MTA
13,7335,40.609056,-73.921494,1,2026-03-31 20:48:10.000,B46,12929.64,12.506850,MTA
14,7960,40.658138,-73.931074,1,2026-03-31 20:48:13.000,B46,7053.42,4.673517,MTA
15,4596,40.608733,-73.921134,1,2026-03-31 20:48:11.000,B46,12929.64,20.506850,MTA
16,7952,40.663328,-73.931609,1,2026-03-31 20:48:16.752,B46,6518.64,-0.283750,MTA
17,7704,40.644654,-73.929624,1,2026-03-31 20:48:03.000,B46,8609.88,14.773517,MTA
18,7652,40.677098,-73.930323,1,2026-03-31 20:48:18.000,B46,5052.26,-6.052433,MTA
19,7026,40.680196,-73.928554,0,2026-03-31 20:48:10.000,B46,8215.23,6.838400,MTA
20,7837,40.656323,-73.930880,0,2026-03-31 20:48:18.000,B46,5557.63,5.524183,MTA
21,7340,40.646000,-73.929775,1,2026-03-31 20:48:18.000,B46,8609.88,6.568217,MTA
22,7325,40.709336,-73.959305,1,2026-03-31 20:48:14.000,B46,225.73,28.375450,MTA
23,7654,40.708049,-73.956883,1,2026-03-31 20:48:11.000,B46,545.75,3.461267,MTA
24,7044,40.658528,-73.931116,0,2026-03-31 20:48:04.000,B46,5870.20,29.922533,MTA
25,7307,40.706828,-73.953338,1,2026-03-31 20:48:21.000,B46,903.73,9.761017,MTA
26,7343,40.635188,-73.928611,0,2026-03-31 20:48:17.000,B46,3289.42,6.757917,MTA
27,7964,40.708621,-73.958483,0,2026-03-31 20:48:10.636,B46,12776.55,12.962467,MTA
28,7932,40.647199,-73.958123,1,2026-03-31 20:48:10.203,B41,6675.78,2.476867,MTA
29,7930,40.672341,-73.968940,0,2026-03-31 20:48:10.124,B41,8328.25,0.860200,MTA
30,7938,40.662866,-73.962223,1,2026-03-31 20:48:14.140,B41,4907.69,3.510200,MTA
31,7317,40.684421,-73.977719,0,2026-03-31 20:48:19.000,B41,10530.34,18.525233,MTA
32,7337,40.676520,-73.971986,1,2026-03-31 20:48:14.000,B41,3208.34,0.626183,MTA
33,7618,40.658886,-73.960523,0,2026-03-31 20:48:15.000,B41,7369.46,0.051233,MTA
34,7520,40.619634,-73.915763,0,2026-03-31 20:48:06.000,B41,715.91,10.810200,MTA
35,7968,40.618641,-73.932540,1,2026-03-31 20:48:21.000,B41,10734.47,7.148717,MTA
36,7013,40.633363,-73.948245,1,2026-03-31 20:48:07.000,B41,8631.14,7.418767,MTA
37,7014,40.641487,-73.956617,0,2026-03-31 20:47:59.000,B41,4854.19,-0.322800,MTA
38,7958,40.611818,-73.924632,0,2026-03-31 20:48:13.293,B41,654.70,-1.627817,MTA
39,7836,40.689136,-73.984457,1,2026-03-31 20:48:03.000,B41,1650.64,-1.076400,MTA
40,7623,40.622028,-73.936255,1,2026-03-31 20:48:06.570,B41,10502.35,2.315750,MTA
41,7935,40.666134,-73.964486,1,2026-03-31 20:48:26.000,B41,4907.69,0.655033,MTA
42,7936,40.687631,-73.980572,1,2026-03-31 20:48:16.246,B41,2139.49,-16.647600,MTA
43,7955,40.658868,-73.960523,0,2026-03-31 20:48:00.624,B41,7750.83,4.388200,MTA
44,7948,40.695805,-73.991035,1,2026-03-31 20:48:04.762,B41,632.55,-1.231683,MTA
45,7694,40.655144,-73.959762,1,2026-03-31 20:48:15.000,B41,6391.20,5.016033,MTA
46,7342,40.626936,-73.941435,1,2026-03-31 20:48:20.000,B41,10074.27,13.512500,MTA
47,7483,40.639292,-73.954455,0,2026-03-31 20:48:00.000,B41,5736.95,55.724300,MTA
48,9450,40.814985,-73.954723,0,2026-03-31 20:48:20.583,M104,7910.61,17.516583,MTA
49,9608,40.784020,-73.979730,0,2026-03-31 20:48:20.000,M104,3397.95,2.516583,MTA
50,9769,40.803693,-73.967169,1,2026-03-31 20:48:11.115,M104,2561.91,2.326350,MTA
51,9767,40.799582,-73.968180,0,2026-03-31 20:48:13.776,M104,5488.53,3.018917,MTA
52,9773,40.779709,-73.981780,1,2026-03-31 20:48:08.718,M104,5575.55,-1.247567,MTA
53,9446,40.765377,-73.980143,1,2026-03-31 20:48:27.364,M104,7520.47,2.806467,MTA
54,9617,40.766721,-73.982806,0,2026-03-31 20:48:02.263,M104,1704.26,0.487700,MTA

In [65]:
#Checking routes
print(mta_df.groupby('route_id').size())

route_id
B41     20
B44     13
B46     15
M104     7
dtype: int64

In [66]:
# Bx12 and M14 missing

requests.get(mta_url, params={"key": MTA_KEY, "LineRef": "MTA NYCT_Bx12"})
requests.get(mta_url, params={"key": MTA_KEY, "LineRef": "MTA NYCT_M14A"})

In [67]:
bx12_response = requests.get(mta_url, params={"key": MTA_KEY, "LineRef": "MTA NYCT_Bx12"})
print(bx12_response.json()['Siri']['ServiceDelivery']['VehicleMonitoringDelivery'][0])

{'ResponseTimestamp': '2026-03-31T20:48:30.324-04:00', 'ErrorCondition': {'OtherError': {'ErrorText': 'No such route: MTA NYCT_Bx12.'}, 'Description': 'No such route: MTA NYCT_Bx12.'}}

In [68]:
m14a_response = requests.get(mta_url, params={"key": MTA_KEY, "LineRef": "MTA NYCT_M14A"})
print(m14a_response.json()['Siri']['ServiceDelivery']['VehicleMonitoringDelivery'][0])

{'ResponseTimestamp': '2026-03-31T20:48:30.381-04:00', 'ErrorCondition': {'OtherError': {'ErrorText': 'No such route: MTA NYCT_M14A.'}, 'Description': 'No such route: MTA NYCT_M14A.'}}

In [69]:
#Testing for correct route names
test_response = requests.get(
    "http://bustime.mta.info/api/where/routes-for-agency/MTA%20NYCT.json",
    params={"key": MTA_KEY}
)
routes = test_response.json()['data']['list']
for r in routes:
    if 'x12' in r['id'].lower() or 'm14' in r['id'].lower():
        print(r['id'], r['shortName'])

MTA NYCT_BX12+ Bx12-SBS
MTA NYCT_BX12 Bx12
MTA NYCT_M14A+ M14A-SBS
MTA NYCT_M14D+ M14D-SBS

In [70]:
mta_routes = ['B44', 'B46', 'B41', 'BX12', 'M14A+', 'M104']
mta_dfs = []

for route in mta_routes:
    mta_params = {"key": MTA_KEY, "LineRef": f"MTA NYCT_{route}"} #This needs to be in the loop not outside
    response = requests.get(mta_url, params=mta_params)
    delivery = response.json()['Siri']['ServiceDelivery']['VehicleMonitoringDelivery'][0]
    mta_vehicles = delivery.get('VehicleActivity', [])  # creating an empty list if no active vehicles (this caused loop to not work)
    
    mta_rows = []
    for vehicle in mta_vehicles:
        mvj = vehicle['MonitoredVehicleJourney']  # the path to data
        if 'MonitoredCall' not in mvj:  # skip buses in layover (this also caused loop to not work)
            continue
        mc = mvj['MonitoredCall']  # the path to data

        if 'ExpectedArrivalTime' not in mc:  # skip vehicles with no prediction (Dropping, won't be able to calc dev)
            continue
        
         # parse both times so it can be subtracted to get dev
        aimed = pd.to_datetime(mc['AimedArrivalTime'])
        expected = pd.to_datetime(mc['ExpectedArrivalTime'])
        
        row = {
            'vehicle_id': mvj['VehicleRef'].replace('MTA NYCT_', ''),  # removing prefix
            'lat': mvj['VehicleLocation']['Latitude'],
            'lon': mvj['VehicleLocation']['Longitude'],
            'direction': int(mvj['DirectionRef']),  # making the string "0"/"1" a int
            'timestamp': pd.to_datetime(vehicle['RecordedAtTime']),
            'route_id': mvj['LineRef'].replace('MTA NYCT_', ''),  # removing prefix
            'call_distance': mc['Extensions']['Distances']['CallDistanceAlongRoute'],  # stop_sequence equivalent
            'deviation': (expected - aimed).total_seconds() / 60  # positive = late, negative = early (var created)
        }
        mta_rows.append(row)
    
    df = pd.DataFrame(mta_rows)
    if df.empty:  # skip if no valid vehicles for this route
        continue
    df['agency'] = 'MTA'
    df['timestamp'] = df['timestamp'].dt.tz_localize(None)  # making timezone to match WMATA/MBTA
    mta_dfs.append(df)

mta_df = pd.concat(mta_dfs, ignore_index=True)
mta_df

,vehicle_id,lat,lon,direction,timestamp,route_id,call_distance,deviation,agency
0,7957,40.699878,-73.953665,1,2026-03-31 20:48:21.000,B44,0.00,11.525567,MTA
1,7330,40.634265,-73.947797,0,2026-03-31 20:48:11.000,B44,6376.46,10.058900,MTA
2,7949,40.641163,-73.948523,1,2026-03-31 20:48:27.474,B44,6630.35,6.738267,MTA
3,7314,40.645319,-73.948979,1,2026-03-31 20:48:06.000,B44,6166.82,2.092233,MTA
4,7015,40.585935,-73.939123,1,2026-03-31 20:48:12.000,B44,12853.20,6.508900,MTA
...,...,...,...,...,...,...,...,...,...
65,9769,40.803693,-73.967169,1,2026-03-31 20:48:11.115,M104,2561.91,2.326350,MTA
66,9767,40.799582,-73.968180,0,2026-03-31 20:48:13.776,M104,5488.53,3.018917,MTA
67,9773,40.779709,-73.981780,1,2026-03-31 20:48:08.718,M104,5575.55,-1.247567,MTA
68,9446,40.765377,-73.980143,1,2026-03-31 20:48:27.364,M104,7520.47,2.806467,MTA
69,9617,40.766721,-73.982806,0,2026-03-31 20:48:02.263,M104,1704.26,0.487700,MTA

In [71]:
print(mta_df.groupby('route_id').size())

route_id
B41      20
B44      13
B46      15
BX12      8
M104      7
M14A+     7
dtype: int64

In [72]:
# Checking that all dfs have the came columns

print("WMATA columns:", wmata_df.columns.tolist())
print("MBTA columns:", mbta_df.columns.tolist())
print("MTA columns:", mta_df.columns.tolist())

WMATA columns: ['vehicle_id', 'lat', 'lon', 'deviation', 'timestamp', 'trip_id', 'route_id', 'direction', 'trip_start_time', 'agency']
MBTA columns: ['vehicle_id', 'lat', 'lon', 'direction', 'timestamp', 'stop_sequence', 'trip_id', 'route_id', 'agency']
MTA columns: ['vehicle_id', 'lat', 'lon', 'direction', 'timestamp', 'route_id', 'call_distance', 'deviation', 'agency']

In [73]:
#Checking var types
print("WMATA\n", wmata_df.dtypes)
print("\nMBTA\n", mbta_df.dtypes)
print("\nMTA\n", mta_df.dtypes)

WMATA
 vehicle_id                 object
lat                       float64
lon                       float64
deviation                 float64
timestamp          datetime64[ns]
trip_id                    object
route_id                   object
direction                   int64
trip_start_time    datetime64[ns]
agency                     object
dtype: object

MBTA
 vehicle_id               object
lat                     float64
lon                     float64
direction                 int64
timestamp        datetime64[ns]
stop_sequence             int64
trip_id                  object
route_id                 object
agency                   object
dtype: object

MTA
 vehicle_id               object
lat                     float64
lon                     float64
direction                 int64
timestamp        datetime64[ns]
route_id                 object
call_distance           float64
deviation               float64
agency                   object
dtype: object

# API Pull - Continuous Loop

WMATA
- High Frequency Routes: D40, D60, D80, C53, C61, D20, P40
- Low Frequency Routes: C81, P16, D24, P14, C23, P20, C35

MBTA
- High Frequency Routes: 1, 23, 28, 39, 57, 66, 111
- Low Frequency Routes: 64, 201, 50, 42, 87, 85, 70

MTA
- High Frequency Routes: B44, B46, B41, BX12, M14A+, M23+, Q98
- Low Frequency Routes: B32, M21, BX42, M50, Q67, B84, Q42

 Note: I added low frequency routes

In [74]:
#Updated Routes
wmata_routes = ['D40', 'D60', 'D80', 'C53', 'C61', 'D20', 'P40', 'C81', 'P16', 'D24', 'P14', 'C23', 'P20', 'C35']
mbta_routes = ['1', '23', '28', '39', '57', '66', '111', '64', '201', '50', '42', '87', '85', '70']
mta_routes = ['B44', 'B46', 'B41', 'BX12', 'M14A+', 'M23+', 'Q98', 'B32', 'M21', 'BX42', 'M50', 'Q67', 'B84', 'Q42']

In [75]:
wmata_fields = {
    'VehicleID': 'vehicle_id',
    'Lat': 'lat',
    'Lon': 'lon',
    'Deviation': 'deviation',
    'DateTime': 'timestamp',
    'TripID': 'trip_id',
    'RouteID': 'route_id',
    'DirectionNum': 'direction',
    'TripStartTime': 'trip_start_time'
}

In [81]:
output_dir = "data"
os.makedirs(output_dir, exist_ok=True)  # creating data folder to store csv

wmata_file = os.path.join(output_dir, "wmata.csv")
mbta_file = os.path.join(output_dir, "mbta.csv")
mta_file = os.path.join(output_dir, "mta.csv")

while True:
    try:
# WMATA
        try: #this allows for the loop to contuine if the pull fails for one agency
            wmata_dfs = []
            for route in wmata_routes:
                wmata_response = requests.get(wmata_url, params={"RouteID": route}, headers=wmata_headers)
                wmata_positions = wmata_response.json()['BusPositions']
                if not wmata_positions:  # skip if no active vehicles
                    continue
                df = pd.DataFrame(wmata_positions)[list(wmata_fields.keys())].rename(columns=wmata_fields)
                df['agency'] = 'WMATA'
                df['timestamp'] = pd.to_datetime(df['timestamp'])
                df['trip_start_time'] = pd.to_datetime(df['trip_start_time'])
                wmata_dfs.append(df)
            if wmata_dfs:
                wmata_df = pd.concat(wmata_dfs, ignore_index=True)
                wmata_df.to_csv(wmata_file, mode='a', header=not os.path.exists(wmata_file), index=False) # appending pulls to exsiting file
        except Exception as e:
            print(f"WMATA error: {e}") #if an error this will print it and move on

# MBTA
        try:
            mbta_dfs = []
            for route in mbta_routes:
                mbta_response = requests.get(mbta_url, params={"filter[route]": route}, headers=mbta_headers)
                mbta_vehicles = mbta_response.json().get('data', [])  # empty list if no active vehicles
                if not mbta_vehicles:  # skip if no active vehicles
                    continue
                mbta_fields = []
                for vehicle in mbta_vehicles:
                    row = {
                        'vehicle_id': vehicle['id'],
                        'lat': vehicle['attributes']['latitude'],
                        'lon': vehicle['attributes']['longitude'],
                        'direction': vehicle['attributes']['direction_id'],
                        'timestamp': vehicle['attributes']['updated_at'],
                        'stop_sequence': vehicle['attributes']['current_stop_sequence'],
                        'trip_id': vehicle['relationships']['trip']['data']['id'],
                        'route_id': vehicle['relationships']['route']['data']['id']
                    }
                    mbta_fields.append(row)
                df = pd.DataFrame(mbta_fields)
                if df.empty:
                    continue
                df['agency'] = 'MBTA'
                df['timestamp'] = pd.to_datetime(df['timestamp']).dt.tz_localize(None)
                mbta_dfs.append(df)
            if mbta_dfs:
                mbta_df = pd.concat(mbta_dfs, ignore_index=True)
                mbta_df.to_csv(mbta_file, mode='a', header=not os.path.exists(mbta_file), index=False)
        except Exception as e:
            print(f"MBTA error: {e}")

# MTA
        try:
            mta_dfs = []
            for route in mta_routes:
                mta_params = {"key": MTA_KEY, "LineRef": f"MTA NYCT_{route}"}  # needs to be in the loop
                response = requests.get(mta_url, params=mta_params)
                delivery = response.json()['Siri']['ServiceDelivery']['VehicleMonitoringDelivery'][0]
                mta_vehicles = delivery.get('VehicleActivity', [])  # empty list if no active vehicles
                mta_rows = []
                for vehicle in mta_vehicles:
                    mvj = vehicle['MonitoredVehicleJourney']  # the path to data
                    if 'MonitoredCall' not in mvj:  # skip buses in layover
                        continue
                    mc = mvj['MonitoredCall']  # the path to data
                    if 'ExpectedArrivalTime' not in mc:  # skip vehicles with no prediction
                        continue
                    # parse both times so it can be subtracted to get dev
                    aimed = pd.to_datetime(mc['AimedArrivalTime'])
                    expected = pd.to_datetime(mc['ExpectedArrivalTime'])
                    row = {
                        'vehicle_id': mvj['VehicleRef'].replace('MTA NYCT_', ''),  # removing prefix
                        'lat': mvj['VehicleLocation']['Latitude'],
                        'lon': mvj['VehicleLocation']['Longitude'],
                        'direction': int(mvj['DirectionRef']),  # making the string "0"/"1" to int
                        'timestamp': pd.to_datetime(vehicle['RecordedAtTime']),
                        'route_id': mvj['LineRef'].replace('MTA NYCT_', ''),  # removing prefix
                        'call_distance': mc['Extensions']['Distances']['CallDistanceAlongRoute'],  # stop_sequence equivalent
                        'deviation': (expected - aimed).total_seconds() / 60  # positive = late, negative = early
                    }
                    mta_rows.append(row)
                df = pd.DataFrame(mta_rows)
                if df.empty:  # skip if no valid vehicles for this route
                    continue
                df['agency'] = 'MTA'
                df['timestamp'] = df['timestamp'].dt.tz_localize(None)  # making timezone to match WMATA/MBTA
                mta_dfs.append(df)
            if mta_dfs:
                mta_df = pd.concat(mta_dfs, ignore_index=True)
                mta_df.to_csv(mta_file, mode='a', header=not os.path.exists(mta_file), index=False)
        except Exception as e:
            print(f"MTA error: {e}")

        print(f"Poll complete: {pd.Timestamp.now().strftime('%H:%M:%S')}")
        time.sleep(60)  # wait 1 minute before next poll

    except KeyboardInterrupt:
        print("Polling stopped.")
        break

Poll complete: 23:04:33
Polling stopped.

### Note:

- Main data collection was done in a different file "api_script" as it auto saves and commits to two different repos
- The above loop will append anything ran to the existing data files (it won't breaking anything by running whats above)

## Cleaning

In [83]:
wmata = pd.read_csv("data/wmata.csv")
mbta = pd.read_csv("data/mbta.csv")
mta = pd.read_csv("data/mta.csv")

/var/folders/mn/ysmjqw4s37x8_rsj533gmd3r0000gn/T/ipykernel_7116/643784603.py:2: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  mbta = pd.read_csv("data/mbta.csv")

In [84]:
print(wmata.groupby('route_id').size().to_string())
print(mbta.groupby('route_id').size().to_string())
print(mta.groupby('route_id').size().to_string())

route_id
C23    23703
C35    24196
C53    95763
C61    48622
C81    29142
D20    48028
D24    26666
D40    69281
D60    54108
D80    96420
P14    18978
P16    24227
P20    18555
P40    42339
route_id
1       58530
8         123
19        200
21         27
23      63977
28      61538
36        202
37        310
38        360
39      53910
42      12879
50       6542
57      57424
64      21645
66      76724
70      48241
85       6115
87      20112
111     67509
201      7304
4050      532
route_id
B32        9642
B41      171006
B44       84577
B46      105249
B84        6403
BX12      39044
BX42      44974
M14A+     45902
M21       14939
M23+      39156
M50       16683
Q42        6764
Q67       24338
Q98       56701

#### WMATA

In [85]:
wmata

,vehicle_id,lat,lon,deviation,timestamp,trip_id,route_id,direction,trip_start_time,agency
0,5509,38.900446,-77.021919,1.0,2026-03-31 12:06:16,4927020,D40,1,2026-03-31 11:12:00,WMATA
1,5515,38.975230,-77.026732,9.0,2026-03-31 12:06:27,6977020,D40,0,2026-03-31 11:12:00,WMATA
2,5522,38.948387,-77.027067,17.0,2026-03-31 12:06:31,25982020,D40,1,2026-03-31 11:24:00,WMATA
3,5517,38.972468,-77.027016,-2.0,2026-03-31 12:06:23,4651020,D40,0,2026-03-31 11:24:00,WMATA
4,5507,38.939690,-77.024966,2.0,2026-03-31 12:06:33,28529020,D40,0,2026-03-31 11:36:00,WMATA
...,...,...,...,...,...,...,...,...,...,...
620023,3315,38.906613,-76.926932,0.0,2026-04-06 22:03:28,29678080,C23,1,2026-04-06 22:00:00,WMATA
620024,7017,39.004999,-76.907630,48.0,2026-04-06 22:03:21,30064080,P20,0,2026-04-06 20:30:00,WMATA
620025,7015,38.957943,-76.868802,57.0,2026-04-06 22:03:04,14090080,P20,0,2026-04-06 21:00:00,WMATA
620026,4775,38.952599,-76.878342,0.0,2026-04-06 22:03:31,7743080,P20,0,2026-04-06 22:00:00,WMATA
620027,4717,38.900909,-76.947258,-1.0,2026-04-06 22:03:06,9682080,C35,0,2026-04-06 21:55:00,WMATA

In [86]:
print(wmata.head())
print(wmata.dtypes)
print(wmata.isnull().sum())

   vehicle_id        lat        lon  deviation            timestamp   trip_id  \
0        5509  38.900446 -77.021919        1.0  2026-03-31 12:06:16   4927020
1        5515  38.975230 -77.026732        9.0  2026-03-31 12:06:27   6977020
2        5522  38.948387 -77.027067       17.0  2026-03-31 12:06:31  25982020
3        5517  38.972468 -77.027016       -2.0  2026-03-31 12:06:23   4651020
4        5507  38.939690 -77.024966        2.0  2026-03-31 12:06:33  28529020

  route_id  direction      trip_start_time agency
0      D40          1  2026-03-31 11:12:00  WMATA
1      D40          0  2026-03-31 11:12:00  WMATA
2      D40          1  2026-03-31 11:24:00  WMATA
3      D40          0  2026-03-31 11:24:00  WMATA
4      D40          0  2026-03-31 11:36:00  WMATA
vehicle_id           int64
lat                float64
lon                float64
deviation          float64
timestamp           object
trip_id              int64
route_id            object
direction            int64
trip_start_time     object
agency              object
dtype: object
vehicle_id         0
lat                0
lon                0
deviation          0
timestamp          0
trip_id            0
route_id           0
direction          0
trip_start_time    0
agency             0
dtype: int64

In [87]:
# fixing dtype
wmata['timestamp'] = pd.to_datetime(wmata['timestamp'])
wmata['trip_start_time'] = pd.to_datetime(wmata['trip_start_time'])
wmata['vehicle_id'] = wmata['vehicle_id'].astype(str)
wmata['trip_id'] = wmata['trip_id'].astype(str)

print(wmata.dtypes)

vehicle_id                 object
lat                       float64
lon                       float64
deviation                 float64
timestamp          datetime64[ns]
trip_id                    object
route_id                   object
direction                   int64
trip_start_time    datetime64[ns]
agency                     object
dtype: object

In [88]:
# Checking for any duplicates(same vehicle at exact same timestamp)
dupes = wmata.duplicated(subset=['vehicle_id', 'timestamp']).sum()
print(f"Duplicates: {dupes}")

Duplicates: 6764

In [91]:
wmata = wmata.drop_duplicates(subset=['vehicle_id', 'timestamp']).copy()
print(wmata.shape)

(613264, 13)

In [93]:
# Creating peak hour and day of the week vars
wmata['hour'] = wmata['timestamp'].dt.hour
wmata['day_of_week'] = wmata['timestamp'].dt.dayofweek  # 0=Monday, 6=Sunday
wmata['peak'] = wmata['hour'].apply(lambda x: 1 if (7 <= x <= 10) or (16 <= x <= 19) else 0) #

print(wmata[['timestamp', 'hour', 'day_of_week', 'peak']].head(10))
print(wmata['peak'].value_counts())

            timestamp  hour  day_of_week  peak
0 2026-03-31 12:06:16    12            1     0
1 2026-03-31 12:06:27    12            1     0
2 2026-03-31 12:06:31    12            1     0
3 2026-03-31 12:06:23    12            1     0
4 2026-03-31 12:06:33    12            1     0
5 2026-03-31 12:06:33    12            1     0
6 2026-03-31 12:06:14    12            1     0
7 2026-03-31 12:06:27    12            1     0
8 2026-03-31 12:06:28    12            1     0
9 2026-03-31 12:06:32    12            1     0
peak
0    337426
1    275838
Name: count, dtype: int64

In [94]:
# Downloading GTFS Static for bunching indicator
import zipfile
import io

gtfs_response = requests.get("https://api.wmata.com/gtfs/bus-gtfs-static.zip", headers=wmata_headers)
z = zipfile.ZipFile(io.BytesIO(gtfs_response.content))
print(z.namelist())

['agency.txt', 'calendar.txt', 'calendar_dates.txt', 'feed_info.txt', 'routes.txt', 'shapes.txt', 'stops.txt', 'stop_times.txt', 'timepoints.txt', 'timepoint_times.txt', 'trips.txt']

In [96]:
# stop_times has scheduled arrivals but no route_id, trips.txt connects trip_id to route_id
stop_times = pd.read_csv(z.open('stop_times.txt'))
trips = pd.read_csv(z.open('trips.txt'))
print(stop_times.head())
print(stop_times.dtypes)
print(trips.head())
print(trips.dtypes)

   trip_id arrival_time departure_time  stop_id  stop_sequence  stop_headsign  \
0     1070      6:00:00        6:00:00     8436              2            NaN
1     1070      6:01:22        6:01:22    21776              3            NaN
2     1070      6:01:56        6:01:56     8328              4            NaN
3     1070      6:02:38        6:02:38    21777              5            NaN
4     1070      6:03:10        6:03:10    19149              6            NaN

   pickup_type  drop_off_type  shape_dist_traveled  timepoint
0            0              0                  NaN          1
1            0              0                  NaN          0
2            0              0                  NaN          0
3            0              0                  NaN          0
4            0              0                  NaN          0
trip_id                  int64
arrival_time            object
departure_time          object
stop_id                  int64
stop_sequence            int64
stop_headsign          float64
pickup_type              int64
drop_off_type            int64
shape_dist_traveled    float64
timepoint                int64
dtype: object
  route_id  service_id   trip_id            trip_headsign  direction_id  \
0      P94           1  18430080  West to National Harbor             1
1      P94           1   1363080         East to Suitland             0
2      P94           1   1498080  West to National Harbor             1
3      P94           1  13235080         East to Suitland             0
4      P94           1  13419080  West to National Harbor             1

  block_id shape_id
0     A001   P94:51
1     A001   P94:03
2     A001   P94:51
3     A001   P94:03
4     A001   P94:51
route_id         object
service_id        int64
trip_id           int64
trip_headsign    object
direction_id      int64
block_id         object
shape_id         object
dtype: object

In [97]:
# filtering to routes needed
# filter trips to only our routes
wmata_trips = trips[trips['route_id'].isin(wmata_routes)]
print(wmata_trips.shape)
print(wmata_trips['route_id'].unique())

(16767, 7)
['D20' 'C35' 'C61' 'D24' 'C81' 'P16' 'P20' 'P40' 'P14' 'D40' 'D60' 'D80'
 'C53' 'C23']

In [98]:
scheduled = stop_times.merge(wmata_trips[['trip_id', 'route_id', 'direction_id']], on='trip_id')
# keeping only first stop per trip since it gives the scheduled departure time for each trip
scheduled = scheduled[scheduled['stop_sequence'] == scheduled.groupby('trip_id')['stop_sequence'].transform('min')]
print(scheduled.shape)
print(scheduled.head())

(16767, 12)
     trip_id arrival_time departure_time  stop_id  stop_sequence  \
0       1070      6:00:00        6:00:00     8436              2
31      1100      6:00:00        6:00:00     8436              2
62      2020      5:00:00        5:00:00    11991              2
92      2040      5:00:00        5:00:00    11991              2
122     2060      5:00:00        5:00:00    11991              2

     stop_headsign  pickup_type  drop_off_type  shape_dist_traveled  \
0              NaN            0              0                  NaN
31             NaN            0              0                  NaN
62             NaN            0              0                  NaN
92             NaN            0              0                  NaN
122            NaN            0              0                  NaN

     timepoint route_id  direction_id
0            1      C61             0
31           1      C61             0
62           1      C61             1
92           1      C61             1
122          1      C61             1

In [99]:
#trips past midnight use times like 25:30:00 instead of 01:30:00 to stay on the same service day on GTFS
scheduled['departure_time'] = pd.to_timedelta(scheduled['departure_time']) # convert departure_time to timedelta since GTFS times can exceed 24:00:00
scheduled = scheduled.sort_values(['route_id', 'direction_id', 'departure_time'])
# calc scheduled headway as gap between consecutive trips on same route/direction (in minutes)
scheduled['scheduled_headway'] = scheduled.groupby(['route_id', 'direction_id'])['departure_time'].diff().dt.total_seconds() / 60

print(scheduled[['route_id', 'direction_id', 'departure_time', 'scheduled_headway']].head(20))

       route_id  direction_id  departure_time  scheduled_headway
331319      C23             0 0 days 06:00:00                NaN
331365      C23             0 0 days 06:00:00                0.0
331411      C23             0 0 days 06:00:00                0.0
331457      C23             0 0 days 06:00:00                0.0
331503      C23             0 0 days 06:00:00                0.0
473534      C23             0 0 days 06:00:00                0.0
473580      C23             0 0 days 06:00:00                0.0
616070      C23             0 0 days 06:00:00                0.0
350581      C23             0 0 days 06:30:00               30.0
350627      C23             0 0 days 06:30:00                0.0
449239      C23             0 0 days 06:30:00                0.0
657396      C23             0 0 days 06:30:00                0.0
657442      C23             0 0 days 06:30:00                0.0
657488      C23             0 0 days 06:30:00                0.0
657534      C23             0 0 days 06:30:00                0.0
657580      C23             0 0 days 06:30:00                0.0
584905      C23             0 0 days 07:00:00               30.0
635042      C23             0 0 days 07:00:00                0.0
635088      C23             0 0 days 07:00:00                0.0
472963      C23             0 0 days 07:10:00               10.0

In [101]:
# multiple trips have the same departure time, shouldn't be the case
print(trips['service_id'].value_counts())
calendar = pd.read_csv(z.open('calendar.txt')) # which service IDs correspond to what day
print(calendar)

service_id
10    13428
9     13425
6     13421
1     13383
3     13379
4     10406
8     10302
2      9840
Name: count, dtype: int64
   service_id  monday  tuesday  wednesday  thursday  friday  saturday  sunday  \
0           1       0        0          0         0       0         0       0
1           2       0        0          0         0       0         0       1
2           3       0        0          0         0       0         0       0
3           4       0        0          0         0       0         0       0
4           6       0        0          0         0       1         0       0
5           8       0        0          0         0       0         1       0
6           9       1        1          0         1       0         0       0
7          10       0        0          1         0       0         0       0

   start_date  end_date
0    20260315  20260613
1    20260315  20260613
2    20260315  20260613
3    20260315  20260613
4    20260315  20260613
5    20260315  20260613
6    20260315  20260613
7    20260315  20260613

In [102]:
# keeping only service IDs with at least one active day
active_serviced = calendar[calendar[['monday','tuesday','wednesday','thursday','friday','saturday','sunday']].sum(axis=1) > 0]['service_id']
print(active_serviced.values)

[ 2  6  8  9 10]

In [104]:
# filtering to only active service days
wmata_trips = trips[trips['route_id'].isin(wmata_routes) & trips['service_id'].isin(active_serviced)]
print(wmata_trips.shape)
print(wmata_trips['service_id'].value_counts())

(10432, 7)
service_id
6     2221
9     2221
10    2221
8     1927
2     1842
Name: count, dtype: int64

In [105]:
scheduled = stop_times.merge(wmata_trips[['trip_id', 'route_id', 'direction_id', 'service_id']], on='trip_id')
scheduled = scheduled[scheduled['stop_sequence'] == scheduled.groupby('trip_id')['stop_sequence'].transform('min')]

scheduled['departure_time'] = pd.to_timedelta(scheduled['departure_time'])

scheduled = scheduled.sort_values(['route_id', 'direction_id', 'service_id', 'departure_time'])
scheduled['scheduled_headway'] = scheduled.groupby(['route_id', 'direction_id', 'service_id'])['departure_time'].diff().dt.total_seconds() / 60

print(scheduled[['route_id', 'direction_id', 'service_id', 'departure_time', 'scheduled_headway']].head(20))

       route_id  direction_id  service_id  departure_time  scheduled_headway
382304      C23             0           2 0 days 06:00:00                NaN
278159      C23             0           2 0 days 06:30:00               30.0
362798      C23             0           2 0 days 07:00:00               30.0
187216      C23             0           2 0 days 07:30:00               30.0
74341       C23             0           2 0 days 08:00:00               30.0
357219      C23             0           2 0 days 08:30:00               30.0
279914      C23             0           2 0 days 09:00:00               30.0
2575        C23             0           2 0 days 09:30:00               30.0
145642      C23             0           2 0 days 10:00:00               30.0
104486      C23             0           2 0 days 10:30:00               30.0
184908      C23             0           2 0 days 11:00:00               30.0
401140      C23             0           2 0 days 11:30:00               30.0
357782      C23             0           2 0 days 12:00:00               30.0
103485      C23             0           2 0 days 12:30:00               30.0
313101      C23             0           2 0 days 13:00:00               30.0
184126      C23             0           2 0 days 13:30:00               30.0
221362      C23             0           2 0 days 14:00:00               30.0
324578      C23             0           2 0 days 14:30:00               30.0
247248      C23             0           2 0 days 15:00:00               30.0
199901      C23             0           2 0 days 15:30:00               30.0

In [106]:
print(wmata['day_of_week'].value_counts().sort_index())

day_of_week
0     95019
1     45810
2    103183
3    103097
4     99448
5     89685
6     77022
Name: count, dtype: int64

In [107]:
# mapping day of week to GTFS service_id based on calendar
day_to_service = {0: 9, 1: 9, 2: 10, 3: 9, 4: 6, 5: 8, 6: 2}
wmata['service_id'] = wmata['day_of_week'].map(day_to_service)
print(wmata['service_id'].value_counts())

service_id
9     243926
10    103183
6      99448
8      89685
2      77022
Name: count, dtype: int64

In [108]:
# converting trip_start_time to timedelta to match GTFS departure_time format
wmata['trip_start_timedelta'] = pd.to_timedelta(wmata['trip_start_time'].dt.strftime('%H:%M:%S'))
print(wmata[['trip_start_time', 'trip_start_timedelta']].head())

      trip_start_time trip_start_timedelta
0 2026-03-31 11:12:00      0 days 11:12:00
1 2026-03-31 11:12:00      0 days 11:12:00
2 2026-03-31 11:24:00      0 days 11:24:00
3 2026-03-31 11:24:00      0 days 11:24:00
4 2026-03-31 11:36:00      0 days 11:36:00

In [109]:
# adding scheduled headway to RT data by route, direction, service day, & trip start time
wmata = wmata.merge(
    scheduled[['route_id', 'direction_id', 'service_id', 'departure_time', 'scheduled_headway']],
    left_on=['route_id', 'direction', 'service_id', 'trip_start_timedelta'],
    right_on=['route_id', 'direction_id', 'service_id', 'departure_time'],
    how='left'
)
print(wmata.shape)
print(wmata['scheduled_headway'].isnull().sum())

(614675, 18)
21468

In [112]:
# which routes have the most nulls
print(wmata[wmata['scheduled_headway'].isnull()].groupby('route_id').size().sort_values(ascending=False))

print(wmata[wmata['scheduled_headway'].isnull()].groupby('route_id')['trip_start_time'].agg(['min', 'max', 'mean']))

route_id
C53    4484
D40    2857
D60    2842
D80    2339
D20    1652
P40    1632
C61    1094
C23    1022
C81     786
P16     606
P20     555
D24     541
P14     534
C35     524
dtype: int64
                         min                 max                          mean
route_id
C23      2026-04-01 06:00:00 2026-04-07 00:00:00 2026-04-03 23:05:19.373776896
C35      2026-04-01 04:41:00 2026-04-07 00:00:00 2026-04-03 17:22:35.381679360
C53      2026-04-01 00:00:00 2026-04-07 00:00:00 2026-04-03 23:45:24.955396864
C61      2026-04-01 00:00:00 2026-04-07 00:00:00 2026-04-03 21:31:57.367458816
C81      2026-04-01 00:00:00 2026-04-07 00:00:00 2026-04-04 02:33:19.847328256
D20      2026-04-01 00:00:00 2026-04-07 00:00:00 2026-04-03 22:14:39.697336320
D24      2026-03-31 00:04:00 2026-04-07 00:00:00 2026-04-03 17:37:14.306839296
D40      2026-04-01 00:00:00 2026-04-07 00:00:00 2026-04-03 21:22:58.676933632
D60      2026-04-01 00:10:00 2026-04-07 00:00:00 2026-04-03 16:16:43.026037760
D80      2026-04-01 00:00:00 2026-04-06 01:45:00 2026-04-03 15:12:25.061992448
P14      2026-04-01 05:00:00 2026-04-06 05:15:00 2026-04-03 15:37:23.258426880
P16      2026-04-01 00:00:00 2026-04-06 05:00:00 2026-04-03 14:46:35.544554496
P20      2026-04-01 00:05:00 2026-04-06 05:24:00 2026-04-03 18:33:28.864865024
P40      2026-03-31 00:05:00 2026-04-06 23:35:00 2026-04-03 13:56:53.088235264

In [113]:
# dropping unmatched rows these are mostly around midnight RT and GTFS date/times don't align
wmata = wmata.dropna(subset=['scheduled_headway'])
print(wmata.shape)

(593207, 18)

In [114]:
# bunching indicator: 1 if actual headway < 50% of scheduled headway
wmata['bunching'] = (wmata['deviation'] > wmata['scheduled_headway'] * 0.5).astype(int)
print(wmata['bunching'].value_counts())

bunching
0    473429
1    119778
Name: count, dtype: int64

In [115]:
wmata

,vehicle_id,lat,lon,deviation,timestamp,trip_id,route_id,direction,trip_start_time,agency,hour,day_of_week,peak,service_id,trip_start_timedelta,direction_id,departure_time,scheduled_headway,bunching
0,5509,38.900446,-77.021919,1.0,2026-03-31 12:06:16,4927020,D40,1,2026-03-31 11:12:00,WMATA,12,1,0,9,0 days 11:12:00,1.0,0 days 11:12:00,12.0,0
1,5515,38.975230,-77.026732,9.0,2026-03-31 12:06:27,6977020,D40,0,2026-03-31 11:12:00,WMATA,12,1,0,9,0 days 11:12:00,0.0,0 days 11:12:00,12.0,1
2,5522,38.948387,-77.027067,17.0,2026-03-31 12:06:31,25982020,D40,1,2026-03-31 11:24:00,WMATA,12,1,0,9,0 days 11:24:00,1.0,0 days 11:24:00,12.0,1
3,5517,38.972468,-77.027016,-2.0,2026-03-31 12:06:23,4651020,D40,0,2026-03-31 11:24:00,WMATA,12,1,0,9,0 days 11:24:00,0.0,0 days 11:24:00,12.0,0
4,5507,38.939690,-77.024966,2.0,2026-03-31 12:06:33,28529020,D40,0,2026-03-31 11:36:00,WMATA,12,1,0,9,0 days 11:36:00,0.0,0 days 11:36:00,12.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
614670,3315,38.906613,-76.926932,0.0,2026-04-06 22:03:28,29678080,C23,1,2026-04-06 22:00:00,WMATA,22,0,0,9,0 days 22:00:00,1.0,0 days 22:00:00,30.0,0
614671,7017,39.004999,-76.907630,48.0,2026-04-06 22:03:21,30064080,P20,0,2026-04-06 20:30:00,WMATA,22,0,0,9,0 days 20:30:00,0.0,0 days 20:30:00,30.0,1
614672,7015,38.957943,-76.868802,57.0,2026-04-06 22:03:04,14090080,P20,0,2026-04-06 21:00:00,WMATA,22,0,0,9,0 days 21:00:00,0.0,0 days 21:00:00,30.0,1
614673,4775,38.952599,-76.878342,0.0,2026-04-06 22:03:31,7743080,P20,0,2026-04-06 22:00:00,WMATA,22,0,0,9,0 days 22:00:00,0.0,0 days 22:00:00,60.0,0
614674,4717,38.900909,-76.947258,-1.0,2026-04-06 22:03:06,9682080,C35,0,2026-04-06 21:55:00,WMATA,22,0,0,9,0 days 21:55:00,0.0,0 days 21:55:00,55.0,0

In [117]:
wmata.to_csv("data/wmata_v1.csv", index=False)
print("saved")

saved

In [118]:
wmata = wmata.drop(columns=['trip_start_timedelta', 'direction_id', 'departure_time'])
wmata

,vehicle_id,lat,lon,deviation,timestamp,trip_id,route_id,direction,trip_start_time,agency,hour,day_of_week,peak,service_id,scheduled_headway,bunching
0,5509,38.900446,-77.021919,1.0,2026-03-31 12:06:16,4927020,D40,1,2026-03-31 11:12:00,WMATA,12,1,0,9,12.0,0
1,5515,38.975230,-77.026732,9.0,2026-03-31 12:06:27,6977020,D40,0,2026-03-31 11:12:00,WMATA,12,1,0,9,12.0,1
2,5522,38.948387,-77.027067,17.0,2026-03-31 12:06:31,25982020,D40,1,2026-03-31 11:24:00,WMATA,12,1,0,9,12.0,1
3,5517,38.972468,-77.027016,-2.0,2026-03-31 12:06:23,4651020,D40,0,2026-03-31 11:24:00,WMATA,12,1,0,9,12.0,0
4,5507,38.939690,-77.024966,2.0,2026-03-31 12:06:33,28529020,D40,0,2026-03-31 11:36:00,WMATA,12,1,0,9,12.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
614670,3315,38.906613,-76.926932,0.0,2026-04-06 22:03:28,29678080,C23,1,2026-04-06 22:00:00,WMATA,22,0,0,9,30.0,0
614671,7017,39.004999,-76.907630,48.0,2026-04-06 22:03:21,30064080,P20,0,2026-04-06 20:30:00,WMATA,22,0,0,9,30.0,1
614672,7015,38.957943,-76.868802,57.0,2026-04-06 22:03:04,14090080,P20,0,2026-04-06 21:00:00,WMATA,22,0,0,9,30.0,1
614673,4775,38.952599,-76.878342,0.0,2026-04-06 22:03:31,7743080,P20,0,2026-04-06 22:00:00,WMATA,22,0,0,9,60.0,0
614674,4717,38.900909,-76.947258,-1.0,2026-04-06 22:03:06,9682080,C35,0,2026-04-06 21:55:00,WMATA,22,0,0,9,55.0,0

In [120]:
wmata.to_csv("data/wmata_clean.csv", index=False)
print("saved")

saved

#### MBTA

In [121]:
mbta

,vehicle_id,lat,lon,direction,timestamp,stop_sequence,trip_id,route_id,agency
0,y3251,42.364823,-71.102914,0,2026-03-31 12:06:40,18.0,73604104,1,MBTA
1,y1903,42.331403,-71.076767,1,2026-03-31 12:06:47,20.0,73604114,1,MBTA
2,y1875,42.358715,-71.093350,0,2026-03-31 12:06:38,15.0,73604103,1,MBTA
3,y1854,42.347308,-71.088111,1,2026-03-31 12:06:45,12.0,73604080,1,MBTA
4,y1849,42.332378,-71.079953,1,2026-03-31 12:06:45,21.0,73604086,1,MBTA
...,...,...,...,...,...,...,...,...,...
564199,y3158,42.378492,-71.092850,1,2026-04-06 22:03:45,31.0,75523316,87,MBTA
564200,y3154,42.381398,-71.099678,0,2026-04-06 22:03:43,7.0,75523472,87,MBTA
564201,y2105,42.363260,-71.132340,1,2026-04-06 22:03:40,39.0,75522396,70,MBTA
564202,y2063,42.364558,-71.175511,0,2026-04-06 22:03:41,22.0,75522317,70,MBTA
564203,y1999,42.376468,-71.253734,1,2026-04-06 22:03:46,4.0,75522289,70,MBTA

In [122]:
print(mbta.head())
print(mbta.dtypes)
print(mbta.isnull().sum())

  vehicle_id        lat        lon  direction            timestamp  \
0      y3251  42.364823 -71.102914          0  2026-03-31 12:06:40
1      y1903  42.331403 -71.076767          1  2026-03-31 12:06:47
2      y1875  42.358715 -71.093350          0  2026-03-31 12:06:38
3      y1854  42.347308 -71.088111          1  2026-03-31 12:06:45
4      y1849  42.332378 -71.079953          1  2026-03-31 12:06:45

   stop_sequence   trip_id  route_id agency
0           18.0  73604104         1   MBTA
1           20.0  73604114         1   MBTA
2           15.0  73604103         1   MBTA
3           12.0  73604080         1   MBTA
4           21.0  73604086         1   MBTA
vehicle_id        object
lat              float64
lon              float64
direction          int64
timestamp         object
stop_sequence    float64
trip_id           object
route_id           int64
agency            object
dtype: object
vehicle_id        0
lat               0
lon               0
direction         0
timestamp         0
stop_sequence    84
trip_id           0
route_id          0
agency            0
dtype: int64

In [125]:
# filtering to routes in mbta_routes
mbta = mbta[mbta['route_id'].isin([int(r) for r in mbta_routes if r.isdigit()] + mbta_routes)].copy()
print(mbta['route_id'].unique())

['1' '23' '28' '39' '57' '66' '111' '64' '201' '50' '42' '87' '70' '85']

In [126]:
mbta['timestamp'] = pd.to_datetime(mbta['timestamp'])
mbta['route_id'] = mbta['route_id'].astype(str)
mbta['trip_id'] = mbta['trip_id'].astype(str)

print(mbta.dtypes)

vehicle_id               object
lat                     float64
lon                     float64
direction                 int64
timestamp        datetime64[ns]
stop_sequence           float64
trip_id                  object
route_id                 object
agency                   object
dtype: object

In [127]:
print(mbta[mbta['stop_sequence'].isnull()][['route_id', 'vehicle_id', 'timestamp']].head(10))

       route_id vehicle_id           timestamp
123156       87      y2029 2026-04-01 19:15:09
256831       66      y1849 2026-04-03 08:05:40
256943       66      y1849 2026-04-03 08:06:57
367801       70      y2015 2026-04-04 13:37:51
367972       70      y2015 2026-04-04 13:40:06
369098       70      y2099 2026-04-04 13:54:29
369184       70      y2099 2026-04-04 13:55:18
369360       70      y2099 2026-04-04 13:57:47
369541       70      y2021 2026-04-04 14:00:03
369625       70      y2021 2026-04-04 14:01:08

In [128]:
# dropping rows with missing stop_sequence 
mbta = mbta.dropna(subset=['stop_sequence'])
mbta['stop_sequence'] = mbta['stop_sequence'].astype(int)
print(mbta.shape)

(562366, 9)

In [130]:
# checking for duplicates
dupes = mbta.duplicated(subset=['vehicle_id', 'timestamp']).sum()
print(f"Duplicates: {dupes}")

mbta = mbta.drop_duplicates(subset=['vehicle_id', 'timestamp']).copy()
print(mbta.shape)

Duplicates: 6061
(556305, 9)

In [131]:
# peak hour and day vars
mbta['hour'] = mbta['timestamp'].dt.hour  
mbta['day_of_week'] = mbta['timestamp'].dt.dayofweek  
mbta['peak'] = mbta['hour'].apply(lambda x: 1 if (7 <= x <= 10) or (16 <= x <= 19) else 0) # 1 if peak, 0 otherwise

print(mbta['peak'].value_counts())

peak
0    302571
1    253734
Name: count, dtype: int64

In [132]:
#GTFS Static
mbta_gtfs = requests.get("https://cdn.mbta.com/MBTA_GTFS.zip", headers=mbta_headers)
z_mbta = zipfile.ZipFile(io.BytesIO(mbta_gtfs.content))
print(z_mbta.namelist())

['agency.txt', 'areas.txt', 'calendar.txt', 'calendar_attributes.txt', 'calendar_dates.txt', 'checkpoints.txt', 'directions.txt', 'facilities.txt', 'facilities_properties.txt', 'facilities_properties_definitions.txt', 'fare_leg_join_rules.txt', 'fare_leg_rules.txt', 'fare_media.txt', 'fare_products.txt', 'fare_transfer_rules.txt', 'feed_info.txt', 'levels.txt', 'lines.txt', 'linked_datasets.txt', 'multi_route_trips.txt', 'pathways.txt', 'route_patterns.txt', 'routes.txt', 'shapes.txt', 'stop_areas.txt', 'stop_times.txt', 'stops.txt', 'timeframes.txt', 'transfers.txt', 'trips.txt', 'trips_properties.txt', 'trips_properties_definitions.txt']

In [133]:
mbta_stop_times = pd.read_csv(z_mbta.open('stop_times.txt'))
mbta_trips = pd.read_csv(z_mbta.open('trips.txt'))
print(mbta_trips.head())
print(mbta_trips.dtypes)
print(mbta_stop_times.head())
print(mbta_stop_times.dtypes)

/var/folders/mn/ysmjqw4s37x8_rsj533gmd3r0000gn/T/ipykernel_7116/179596945.py:1: DtypeWarning: Columns (0,3,5) have mixed types. Specify dtype option on import or set low_memory=False.
  mbta_stop_times = pd.read_csv(z_mbta.open('stop_times.txt'))

  route_id                     service_id   trip_id trip_headsign  \
0        1  BUS12026-hbc16016-Saturday-02  73390421       Harvard
1        1  BUS12026-hbc16016-Saturday-02  73390422       Harvard
2        1  BUS12026-hbc16016-Saturday-02  73390423       Harvard
3        1  BUS12026-hbc16016-Saturday-02  73390424       Harvard
4        1  BUS12026-hbc16016-Saturday-02  73390425       Harvard

  trip_short_name  direction_id block_id shape_id  wheelchair_accessible  \
0             NaN             0    C01-4   010154                      1
1             NaN             0   C01-14   010154                      1
2             NaN             0   C01-14   010154                      1
3             NaN             0    C01-3   010154                      1
4             NaN             0    C01-2   010154                      1

   trip_route_type route_pattern_id  bikes_allowed
0              NaN            1-_-0              1
1              NaN            1-_-0              1
2              NaN            1-_-0              1
3              NaN            1-_-0              1
4              NaN            1-_-0              1
route_id                  object
service_id                object
trip_id                   object
trip_headsign             object
trip_short_name           object
direction_id               int64
block_id                  object
shape_id                  object
wheelchair_accessible      int64
trip_route_type          float64
route_pattern_id          object
bikes_allowed              int64
dtype: object
    trip_id arrival_time departure_time stop_id  stop_sequence stop_headsign  \
0  72798582     05:15:00       05:15:00   70036              1           NaN
1  72798582     05:16:00       05:16:00   70034             10           NaN
2  72798582     05:20:00       05:20:00   70032             20           NaN
3  72798582     05:22:00       05:22:00   70278             30           NaN
4  72798582     05:24:00       05:24:00   70030             40           NaN

   pickup_type  drop_off_type  timepoint checkpoint_id  continuous_pickup  \
0            0              1          0         ogmnl                NaN
1            0              0          0         mlmnl                NaN
2            0              0          0         welln                NaN
3            0              0          0         astao                NaN
4            0              0          0          sull                NaN

   continuous_drop_off
0                  NaN
1                  NaN
2                  NaN
3                  NaN
4                  NaN
trip_id                 object
arrival_time            object
departure_time          object
stop_id                 object
stop_sequence            int64
stop_headsign           object
pickup_type              int64
drop_off_type            int64
timepoint                int64
checkpoint_id           object
continuous_pickup      float64
continuous_drop_off    float64
dtype: object

/var/folders/mn/ysmjqw4s37x8_rsj533gmd3r0000gn/T/ipykernel_7116/179596945.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  mbta_trips = pd.read_csv(z_mbta.open('trips.txt'))

In [135]:
# Checking service ID structure
mbta_calendar = pd.read_csv(z_mbta.open('calendar.txt'))
print(mbta_calendar.head(10))

                      service_id  monday  tuesday  wednesday  thursday  \
0  BUS12026-hbb16016-Saturday-02       0        0          0         0
1   BUS12026-hbb16fr1-Weekday-02       0        0          0         0
2   BUS12026-hbb16wk1-Weekday-02       1        1          1         1
3  BUS12026-hbc16016-Saturday-02       0        0          0         0
4   BUS12026-hbc16fr1-Weekday-02       0        0          0         0
5   BUS12026-hbc16wk1-Weekday-02       1        1          1         1
6  BUS12026-hbg16016-Saturday-02       0        0          0         0
7   BUS12026-hbg16fr1-Weekday-02       0        0          0         0
8   BUS12026-hbg16wk1-Weekday-02       1        1          1         1
9  BUS12026-hbl16016-Saturday-02       0        0          0         0

   friday  saturday  sunday  start_date  end_date
0       0         1       0    20260404  20260404
1       1         0       0    20260403  20260403
2       0         0       0    20260330  20260402
3       0         1       0    20260404  20260404
4       1         0       0    20260403  20260403
5       0         0       0    20260330  20260402
6       0         1       0    20260404  20260404
7       1         0       0    20260403  20260403
8       0         0       0    20260330  20260402
9       0         1       0    20260404  20260404

## Resources

- Standardizing time zones:

https://pandas.pydata.org/docs/reference/api/pandas.Series.dt.tz_localize.html

- If continue and break statements:

https://www.educative.io/answers/what-are-break-continue-and-pass-statements-in-python?utm_campaign=Pmax_feb25&utm_source=google&utm_medium=ppc&utm_content=&utm_term=&eid=5082902844932096&utm_term=&utm_campaign=%5BMar+25%5D+Pmax.+-+Coding+Interview+Prep&utm_source=adwords&utm_medium=ppc&hsa_acc=5451446008&hsa_cam=22344713166&hsa_grp=&hsa_ad=&hsa_src=x&hsa_tgt=&hsa_kw=&hsa_mt=&hsa_net=adwords&hsa_ver=3&gad_source=1&gad_campaignid=22354833079&gbraid=0AAAAADfWLuSny8RMeOlF5ThZ04eXKwptZ&gclid=CjwKCAjwvqjOBhAGEiwAngeQnVWlwZMFRhHCXD6ekkGarMTrSQa1YzFdylNc3-Rritp4jo-j1r1iWRoCCMoQAvD_BwE

- Timing Loops

https://www.digitalocean.com/community/tutorials/python-time-sleep

- Try Except

https://www.w3schools.com/python/python_try_except.asp
https://www.reddit.com/r/learnpython/comments/1blfl9e/explain_try_except_structure_in_practical_examples/
https://stackoverflow.com/questions/62062226/how-to-work-with-try-and-except-in-python
https://docs.python.org/3/tutorial/errors.html   
 https://stackoverflow.com/questions/21120947/catching-keyboardinterrupt-in-python-during-program-shutdown

- Auto Commit

https://docs.github.com/en/authentication/connecting-to-github-with-ssh
 https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
 https://discourse.jupyter.org/t/how-to-run-a-notebook-using-command-line/3475
 https://stackoverflow.com/questions/5620525/git-pushing-to-two-repos-in-one-command
 https://stackoverflow.com/questions/4255865/git-push-to-multiple-repositories-simultaneously
 

- Peak Hour & Day

https://www.reddit.com/r/learnpython/comments/1g0ktqk/can_someone_explain_lambda_to_a_beginner/
https://stackoverflow.com/questions/42977395/pandas-dt-hour-formatting
https://docs.dask.org/en/latest/generated/dask.dataframe.Series.dt.dayofweek.html 
https://stackoverflow.com/questions/69973084/is-there-a-difference-between-pd-series-dt-weekday-vs-pd-series-dt-dayofweek 

- GTFS Reference

https://gtfs.org/documentation/realtime/reference/